pub mod driver;
pub use driver::compile_design;
pub mod ascii;
mod display_ast;
pub mod mir;
mod rhif_passes;
mod rtl_passes;
mod stage1;
mod stage2;
mod stage3;
pub use stage1::CompilationMode;
mod lower_rhif_to_rtl;
mod ntl_passes;
pub use stage3::optimize_ntl;
