mod digital;
mod utils;
pub use digital::derive_digital;
mod digital_enum;
mod kernel;
pub use kernel::hdl_kernel;
mod circuit;
mod suffix;
pub use circuit::derive_circuit;
mod circuit_dq;
pub use circuit_dq::derive_circuit_dq;
mod timed;
pub use timed::derive_timed;
mod synchronous;
pub use synchronous::derive_synchronous;
mod synchronous_dq;
pub use synchronous_dq::derive_synchronous_dq;
mod clone;
mod export;
pub mod typenum_traits;
pub use export::export_macro;
pub use typenum_traits::impl_add_trait;
pub use typenum_traits::impl_log2_trait;
pub use typenum_traits::impl_max_trait;
pub use typenum_traits::impl_min_trait;
pub use typenum_traits::impl_sub_trait;
mod partial_eq;
