mod digital;
mod utils;
pub use digital::derive_digital;
mod digital_enum;
mod kernel;
pub use kernel::hdl_kernel;
mod circuit;
mod suffix;
pub use circuit::derive_circuit;
mod circuit_dqz;
pub use circuit_dqz::derive_circuit_dqz;
mod timed;
pub use timed::derive_timed;
mod synchronous;
pub use synchronous::derive_synchronous;
mod synchronous_dqz;
pub use synchronous_dqz::derive_synchronous_dqz;
mod notable;
mod notable_enum;
pub use notable::derive_notable;
