// Autogenerated testbench for kernel_do_stuff
module testbench();
    wire [11:0] out;
    reg [7:0] arg_0;
    assign out = kernel_do_stuff(arg_0);
    initial begin
        arg_0 = 8'b00000000;
        #0;
        if (12'b000000000001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 0", 12'b000000000001, out);
            $finish;
        end
        arg_0 = 8'b00000001;
        #0;
        if (12'b000000000010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 1", 12'b000000000010, out);
            $finish;
        end
        arg_0 = 8'b00000010;
        #0;
        if (12'b000000000011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 2", 12'b000000000011, out);
            $finish;
        end
        arg_0 = 8'b00000011;
        #0;
        if (12'b000000000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 3", 12'b000000000100, out);
            $finish;
        end
        arg_0 = 8'b00000100;
        #0;
        if (12'b000000000101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 4", 12'b000000000101, out);
            $finish;
        end
        arg_0 = 8'b00000101;
        #0;
        if (12'b000000000110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 5", 12'b000000000110, out);
            $finish;
        end
        arg_0 = 8'b00000110;
        #0;
        if (12'b000000000111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 6", 12'b000000000111, out);
            $finish;
        end
        arg_0 = 8'b00000111;
        #0;
        if (12'b000000001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 7", 12'b000000001000, out);
            $finish;
        end
        arg_0 = 8'b00001000;
        #0;
        if (12'b000000001001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 8", 12'b000000001001, out);
            $finish;
        end
        arg_0 = 8'b00001001;
        #0;
        if (12'b000000001010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 9", 12'b000000001010, out);
            $finish;
        end
        arg_0 = 8'b00001010;
        #0;
        if (12'b000000001011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 10", 12'b000000001011, out);
            $finish;
        end
        arg_0 = 8'b00001011;
        #0;
        if (12'b000000001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 11", 12'b000000001100, out);
            $finish;
        end
        arg_0 = 8'b00001100;
        #0;
        if (12'b000000001101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 12", 12'b000000001101, out);
            $finish;
        end
        arg_0 = 8'b00001101;
        #0;
        if (12'b000000001110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 13", 12'b000000001110, out);
            $finish;
        end
        arg_0 = 8'b00001110;
        #0;
        if (12'b000000001111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 14", 12'b000000001111, out);
            $finish;
        end
        arg_0 = 8'b00001111;
        #0;
        if (12'b000000010000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 15", 12'b000000010000, out);
            $finish;
        end
        arg_0 = 8'b00010000;
        #0;
        if (12'b000000010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 16", 12'b000000010001, out);
            $finish;
        end
        arg_0 = 8'b00010001;
        #0;
        if (12'b000000010010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 17", 12'b000000010010, out);
            $finish;
        end
        arg_0 = 8'b00010010;
        #0;
        if (12'b000000010011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 18", 12'b000000010011, out);
            $finish;
        end
        arg_0 = 8'b00010011;
        #0;
        if (12'b000000010100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 19", 12'b000000010100, out);
            $finish;
        end
        arg_0 = 8'b00010100;
        #0;
        if (12'b000000010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 20", 12'b000000010101, out);
            $finish;
        end
        arg_0 = 8'b00010101;
        #0;
        if (12'b000000010110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 21", 12'b000000010110, out);
            $finish;
        end
        arg_0 = 8'b00010110;
        #0;
        if (12'b000000010111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 22", 12'b000000010111, out);
            $finish;
        end
        arg_0 = 8'b00010111;
        #0;
        if (12'b000000011000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 23", 12'b000000011000, out);
            $finish;
        end
        arg_0 = 8'b00011000;
        #0;
        if (12'b000000011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 24", 12'b000000011001, out);
            $finish;
        end
        arg_0 = 8'b00011001;
        #0;
        if (12'b000000011010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 25", 12'b000000011010, out);
            $finish;
        end
        arg_0 = 8'b00011010;
        #0;
        if (12'b000000011011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 26", 12'b000000011011, out);
            $finish;
        end
        arg_0 = 8'b00011011;
        #0;
        if (12'b000000011100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 27", 12'b000000011100, out);
            $finish;
        end
        arg_0 = 8'b00011100;
        #0;
        if (12'b000000011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 28", 12'b000000011101, out);
            $finish;
        end
        arg_0 = 8'b00011101;
        #0;
        if (12'b000000011110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 29", 12'b000000011110, out);
            $finish;
        end
        arg_0 = 8'b00011110;
        #0;
        if (12'b000000011111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 30", 12'b000000011111, out);
            $finish;
        end
        arg_0 = 8'b00011111;
        #0;
        if (12'b000000100000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 31", 12'b000000100000, out);
            $finish;
        end
        arg_0 = 8'b00100000;
        #0;
        if (12'b000000100001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 32", 12'b000000100001, out);
            $finish;
        end
        arg_0 = 8'b00100001;
        #0;
        if (12'b000000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 33", 12'b000000100010, out);
            $finish;
        end
        arg_0 = 8'b00100010;
        #0;
        if (12'b000000100011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 34", 12'b000000100011, out);
            $finish;
        end
        arg_0 = 8'b00100011;
        #0;
        if (12'b000000100100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 35", 12'b000000100100, out);
            $finish;
        end
        arg_0 = 8'b00100100;
        #0;
        if (12'b000000100101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 36", 12'b000000100101, out);
            $finish;
        end
        arg_0 = 8'b00100101;
        #0;
        if (12'b000000100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 37", 12'b000000100110, out);
            $finish;
        end
        arg_0 = 8'b00100110;
        #0;
        if (12'b000000100111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 38", 12'b000000100111, out);
            $finish;
        end
        arg_0 = 8'b00100111;
        #0;
        if (12'b000000101000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 39", 12'b000000101000, out);
            $finish;
        end
        arg_0 = 8'b00101000;
        #0;
        if (12'b000000101001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 40", 12'b000000101001, out);
            $finish;
        end
        arg_0 = 8'b00101001;
        #0;
        if (12'b000000101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 41", 12'b000000101010, out);
            $finish;
        end
        arg_0 = 8'b00101010;
        #0;
        if (12'b000000101011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 42", 12'b000000101011, out);
            $finish;
        end
        arg_0 = 8'b00101011;
        #0;
        if (12'b000000101100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 43", 12'b000000101100, out);
            $finish;
        end
        arg_0 = 8'b00101100;
        #0;
        if (12'b000000101101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 44", 12'b000000101101, out);
            $finish;
        end
        arg_0 = 8'b00101101;
        #0;
        if (12'b000000101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 45", 12'b000000101110, out);
            $finish;
        end
        arg_0 = 8'b00101110;
        #0;
        if (12'b000000101111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 46", 12'b000000101111, out);
            $finish;
        end
        arg_0 = 8'b00101111;
        #0;
        if (12'b000000110000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 47", 12'b000000110000, out);
            $finish;
        end
        arg_0 = 8'b00110000;
        #0;
        if (12'b000000110001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 48", 12'b000000110001, out);
            $finish;
        end
        arg_0 = 8'b00110001;
        #0;
        if (12'b000000110010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 49", 12'b000000110010, out);
            $finish;
        end
        arg_0 = 8'b00110010;
        #0;
        if (12'b000000110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 50", 12'b000000110011, out);
            $finish;
        end
        arg_0 = 8'b00110011;
        #0;
        if (12'b000000110100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 51", 12'b000000110100, out);
            $finish;
        end
        arg_0 = 8'b00110100;
        #0;
        if (12'b000000110101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 52", 12'b000000110101, out);
            $finish;
        end
        arg_0 = 8'b00110101;
        #0;
        if (12'b000000110110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 53", 12'b000000110110, out);
            $finish;
        end
        arg_0 = 8'b00110110;
        #0;
        if (12'b000000110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 54", 12'b000000110111, out);
            $finish;
        end
        arg_0 = 8'b00110111;
        #0;
        if (12'b000000111000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 55", 12'b000000111000, out);
            $finish;
        end
        arg_0 = 8'b00111000;
        #0;
        if (12'b000000111001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 56", 12'b000000111001, out);
            $finish;
        end
        arg_0 = 8'b00111001;
        #0;
        if (12'b000000111010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 57", 12'b000000111010, out);
            $finish;
        end
        arg_0 = 8'b00111010;
        #0;
        if (12'b000000111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 58", 12'b000000111011, out);
            $finish;
        end
        arg_0 = 8'b00111011;
        #0;
        if (12'b000000111100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 59", 12'b000000111100, out);
            $finish;
        end
        arg_0 = 8'b00111100;
        #0;
        if (12'b000000111101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 60", 12'b000000111101, out);
            $finish;
        end
        arg_0 = 8'b00111101;
        #0;
        if (12'b000000111110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 61", 12'b000000111110, out);
            $finish;
        end
        arg_0 = 8'b00111110;
        #0;
        if (12'b000000111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 62", 12'b000000111111, out);
            $finish;
        end
        arg_0 = 8'b00111111;
        #0;
        if (12'b000001000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 63", 12'b000001000000, out);
            $finish;
        end
        arg_0 = 8'b01000000;
        #0;
        if (12'b000001000001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 64", 12'b000001000001, out);
            $finish;
        end
        arg_0 = 8'b01000001;
        #0;
        if (12'b000001000010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 65", 12'b000001000010, out);
            $finish;
        end
        arg_0 = 8'b01000010;
        #0;
        if (12'b000001000011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 66", 12'b000001000011, out);
            $finish;
        end
        arg_0 = 8'b01000011;
        #0;
        if (12'b000001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 67", 12'b000001000100, out);
            $finish;
        end
        arg_0 = 8'b01000100;
        #0;
        if (12'b000001000101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 68", 12'b000001000101, out);
            $finish;
        end
        arg_0 = 8'b01000101;
        #0;
        if (12'b000001000110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 69", 12'b000001000110, out);
            $finish;
        end
        arg_0 = 8'b01000110;
        #0;
        if (12'b000001000111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 70", 12'b000001000111, out);
            $finish;
        end
        arg_0 = 8'b01000111;
        #0;
        if (12'b000001001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 71", 12'b000001001000, out);
            $finish;
        end
        arg_0 = 8'b01001000;
        #0;
        if (12'b000001001001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 72", 12'b000001001001, out);
            $finish;
        end
        arg_0 = 8'b01001001;
        #0;
        if (12'b000001001010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 73", 12'b000001001010, out);
            $finish;
        end
        arg_0 = 8'b01001010;
        #0;
        if (12'b000001001011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 74", 12'b000001001011, out);
            $finish;
        end
        arg_0 = 8'b01001011;
        #0;
        if (12'b000001001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 75", 12'b000001001100, out);
            $finish;
        end
        arg_0 = 8'b01001100;
        #0;
        if (12'b000001001101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 76", 12'b000001001101, out);
            $finish;
        end
        arg_0 = 8'b01001101;
        #0;
        if (12'b000001001110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 77", 12'b000001001110, out);
            $finish;
        end
        arg_0 = 8'b01001110;
        #0;
        if (12'b000001001111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 78", 12'b000001001111, out);
            $finish;
        end
        arg_0 = 8'b01001111;
        #0;
        if (12'b000001010000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 79", 12'b000001010000, out);
            $finish;
        end
        arg_0 = 8'b01010000;
        #0;
        if (12'b000001010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 80", 12'b000001010001, out);
            $finish;
        end
        arg_0 = 8'b01010001;
        #0;
        if (12'b000001010010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 81", 12'b000001010010, out);
            $finish;
        end
        arg_0 = 8'b01010010;
        #0;
        if (12'b000001010011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 82", 12'b000001010011, out);
            $finish;
        end
        arg_0 = 8'b01010011;
        #0;
        if (12'b000001010100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 83", 12'b000001010100, out);
            $finish;
        end
        arg_0 = 8'b01010100;
        #0;
        if (12'b000001010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 84", 12'b000001010101, out);
            $finish;
        end
        arg_0 = 8'b01010101;
        #0;
        if (12'b000001010110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 85", 12'b000001010110, out);
            $finish;
        end
        arg_0 = 8'b01010110;
        #0;
        if (12'b000001010111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 86", 12'b000001010111, out);
            $finish;
        end
        arg_0 = 8'b01010111;
        #0;
        if (12'b000001011000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 87", 12'b000001011000, out);
            $finish;
        end
        arg_0 = 8'b01011000;
        #0;
        if (12'b000001011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 88", 12'b000001011001, out);
            $finish;
        end
        arg_0 = 8'b01011001;
        #0;
        if (12'b000001011010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 89", 12'b000001011010, out);
            $finish;
        end
        arg_0 = 8'b01011010;
        #0;
        if (12'b000001011011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 90", 12'b000001011011, out);
            $finish;
        end
        arg_0 = 8'b01011011;
        #0;
        if (12'b000001011100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 91", 12'b000001011100, out);
            $finish;
        end
        arg_0 = 8'b01011100;
        #0;
        if (12'b000001011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 92", 12'b000001011101, out);
            $finish;
        end
        arg_0 = 8'b01011101;
        #0;
        if (12'b000001011110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 93", 12'b000001011110, out);
            $finish;
        end
        arg_0 = 8'b01011110;
        #0;
        if (12'b000001011111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 94", 12'b000001011111, out);
            $finish;
        end
        arg_0 = 8'b01011111;
        #0;
        if (12'b000001100000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 95", 12'b000001100000, out);
            $finish;
        end
        arg_0 = 8'b01100000;
        #0;
        if (12'b000001100001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 96", 12'b000001100001, out);
            $finish;
        end
        arg_0 = 8'b01100001;
        #0;
        if (12'b000001100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 97", 12'b000001100010, out);
            $finish;
        end
        arg_0 = 8'b01100010;
        #0;
        if (12'b000001100011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 98", 12'b000001100011, out);
            $finish;
        end
        arg_0 = 8'b01100011;
        #0;
        if (12'b000001100100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 99", 12'b000001100100, out);
            $finish;
        end
        arg_0 = 8'b01100100;
        #0;
        if (12'b000001100101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 100", 12'b000001100101, out);
            $finish;
        end
        arg_0 = 8'b01100101;
        #0;
        if (12'b000001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 101", 12'b000001100110, out);
            $finish;
        end
        arg_0 = 8'b01100110;
        #0;
        if (12'b000001100111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 102", 12'b000001100111, out);
            $finish;
        end
        arg_0 = 8'b01100111;
        #0;
        if (12'b000001101000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 103", 12'b000001101000, out);
            $finish;
        end
        arg_0 = 8'b01101000;
        #0;
        if (12'b000001101001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 104", 12'b000001101001, out);
            $finish;
        end
        arg_0 = 8'b01101001;
        #0;
        if (12'b000001101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 105", 12'b000001101010, out);
            $finish;
        end
        arg_0 = 8'b01101010;
        #0;
        if (12'b000001101011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 106", 12'b000001101011, out);
            $finish;
        end
        arg_0 = 8'b01101011;
        #0;
        if (12'b000001101100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 107", 12'b000001101100, out);
            $finish;
        end
        arg_0 = 8'b01101100;
        #0;
        if (12'b000001101101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 108", 12'b000001101101, out);
            $finish;
        end
        arg_0 = 8'b01101101;
        #0;
        if (12'b000001101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 109", 12'b000001101110, out);
            $finish;
        end
        arg_0 = 8'b01101110;
        #0;
        if (12'b000001101111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 110", 12'b000001101111, out);
            $finish;
        end
        arg_0 = 8'b01101111;
        #0;
        if (12'b000001110000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 111", 12'b000001110000, out);
            $finish;
        end
        arg_0 = 8'b01110000;
        #0;
        if (12'b000001110001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 112", 12'b000001110001, out);
            $finish;
        end
        arg_0 = 8'b01110001;
        #0;
        if (12'b000001110010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 113", 12'b000001110010, out);
            $finish;
        end
        arg_0 = 8'b01110010;
        #0;
        if (12'b000001110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 114", 12'b000001110011, out);
            $finish;
        end
        arg_0 = 8'b01110011;
        #0;
        if (12'b000001110100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 115", 12'b000001110100, out);
            $finish;
        end
        arg_0 = 8'b01110100;
        #0;
        if (12'b000001110101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 116", 12'b000001110101, out);
            $finish;
        end
        arg_0 = 8'b01110101;
        #0;
        if (12'b000001110110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 117", 12'b000001110110, out);
            $finish;
        end
        arg_0 = 8'b01110110;
        #0;
        if (12'b000001110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 118", 12'b000001110111, out);
            $finish;
        end
        arg_0 = 8'b01110111;
        #0;
        if (12'b000001111000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 119", 12'b000001111000, out);
            $finish;
        end
        arg_0 = 8'b01111000;
        #0;
        if (12'b000001111001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 120", 12'b000001111001, out);
            $finish;
        end
        arg_0 = 8'b01111001;
        #0;
        if (12'b000001111010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 121", 12'b000001111010, out);
            $finish;
        end
        arg_0 = 8'b01111010;
        #0;
        if (12'b000001111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 122", 12'b000001111011, out);
            $finish;
        end
        arg_0 = 8'b01111011;
        #0;
        if (12'b000001111100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 123", 12'b000001111100, out);
            $finish;
        end
        arg_0 = 8'b01111100;
        #0;
        if (12'b000001111101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 124", 12'b000001111101, out);
            $finish;
        end
        arg_0 = 8'b01111101;
        #0;
        if (12'b000001111110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 125", 12'b000001111110, out);
            $finish;
        end
        arg_0 = 8'b01111110;
        #0;
        if (12'b000001111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 126", 12'b000001111111, out);
            $finish;
        end
        arg_0 = 8'b01111111;
        #0;
        if (12'b000010000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 127", 12'b000010000000, out);
            $finish;
        end
        arg_0 = 8'b10000000;
        #0;
        if (12'b000010000001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 128", 12'b000010000001, out);
            $finish;
        end
        arg_0 = 8'b10000001;
        #0;
        if (12'b000010000010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 129", 12'b000010000010, out);
            $finish;
        end
        arg_0 = 8'b10000010;
        #0;
        if (12'b000010000011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 130", 12'b000010000011, out);
            $finish;
        end
        arg_0 = 8'b10000011;
        #0;
        if (12'b000010000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 131", 12'b000010000100, out);
            $finish;
        end
        arg_0 = 8'b10000100;
        #0;
        if (12'b000010000101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 132", 12'b000010000101, out);
            $finish;
        end
        arg_0 = 8'b10000101;
        #0;
        if (12'b000010000110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 133", 12'b000010000110, out);
            $finish;
        end
        arg_0 = 8'b10000110;
        #0;
        if (12'b000010000111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 134", 12'b000010000111, out);
            $finish;
        end
        arg_0 = 8'b10000111;
        #0;
        if (12'b000010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 135", 12'b000010001000, out);
            $finish;
        end
        arg_0 = 8'b10001000;
        #0;
        if (12'b000010001001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 136", 12'b000010001001, out);
            $finish;
        end
        arg_0 = 8'b10001001;
        #0;
        if (12'b000010001010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 137", 12'b000010001010, out);
            $finish;
        end
        arg_0 = 8'b10001010;
        #0;
        if (12'b000010001011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 138", 12'b000010001011, out);
            $finish;
        end
        arg_0 = 8'b10001011;
        #0;
        if (12'b000010001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 139", 12'b000010001100, out);
            $finish;
        end
        arg_0 = 8'b10001100;
        #0;
        if (12'b000010001101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 140", 12'b000010001101, out);
            $finish;
        end
        arg_0 = 8'b10001101;
        #0;
        if (12'b000010001110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 141", 12'b000010001110, out);
            $finish;
        end
        arg_0 = 8'b10001110;
        #0;
        if (12'b000010001111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 142", 12'b000010001111, out);
            $finish;
        end
        arg_0 = 8'b10001111;
        #0;
        if (12'b000010010000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 143", 12'b000010010000, out);
            $finish;
        end
        arg_0 = 8'b10010000;
        #0;
        if (12'b000010010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 144", 12'b000010010001, out);
            $finish;
        end
        arg_0 = 8'b10010001;
        #0;
        if (12'b000010010010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 145", 12'b000010010010, out);
            $finish;
        end
        arg_0 = 8'b10010010;
        #0;
        if (12'b000010010011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 146", 12'b000010010011, out);
            $finish;
        end
        arg_0 = 8'b10010011;
        #0;
        if (12'b000010010100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 147", 12'b000010010100, out);
            $finish;
        end
        arg_0 = 8'b10010100;
        #0;
        if (12'b000010010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 148", 12'b000010010101, out);
            $finish;
        end
        arg_0 = 8'b10010101;
        #0;
        if (12'b000010010110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 149", 12'b000010010110, out);
            $finish;
        end
        arg_0 = 8'b10010110;
        #0;
        if (12'b000010010111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 150", 12'b000010010111, out);
            $finish;
        end
        arg_0 = 8'b10010111;
        #0;
        if (12'b000010011000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 151", 12'b000010011000, out);
            $finish;
        end
        arg_0 = 8'b10011000;
        #0;
        if (12'b000010011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 152", 12'b000010011001, out);
            $finish;
        end
        arg_0 = 8'b10011001;
        #0;
        if (12'b000010011010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 153", 12'b000010011010, out);
            $finish;
        end
        arg_0 = 8'b10011010;
        #0;
        if (12'b000010011011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 154", 12'b000010011011, out);
            $finish;
        end
        arg_0 = 8'b10011011;
        #0;
        if (12'b000010011100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 155", 12'b000010011100, out);
            $finish;
        end
        arg_0 = 8'b10011100;
        #0;
        if (12'b000010011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 156", 12'b000010011101, out);
            $finish;
        end
        arg_0 = 8'b10011101;
        #0;
        if (12'b000010011110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 157", 12'b000010011110, out);
            $finish;
        end
        arg_0 = 8'b10011110;
        #0;
        if (12'b000010011111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 158", 12'b000010011111, out);
            $finish;
        end
        arg_0 = 8'b10011111;
        #0;
        if (12'b000010100000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 159", 12'b000010100000, out);
            $finish;
        end
        arg_0 = 8'b10100000;
        #0;
        if (12'b000010100001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 160", 12'b000010100001, out);
            $finish;
        end
        arg_0 = 8'b10100001;
        #0;
        if (12'b000010100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 161", 12'b000010100010, out);
            $finish;
        end
        arg_0 = 8'b10100010;
        #0;
        if (12'b000010100011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 162", 12'b000010100011, out);
            $finish;
        end
        arg_0 = 8'b10100011;
        #0;
        if (12'b000010100100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 163", 12'b000010100100, out);
            $finish;
        end
        arg_0 = 8'b10100100;
        #0;
        if (12'b000010100101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 164", 12'b000010100101, out);
            $finish;
        end
        arg_0 = 8'b10100101;
        #0;
        if (12'b000010100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 165", 12'b000010100110, out);
            $finish;
        end
        arg_0 = 8'b10100110;
        #0;
        if (12'b000010100111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 166", 12'b000010100111, out);
            $finish;
        end
        arg_0 = 8'b10100111;
        #0;
        if (12'b000010101000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 167", 12'b000010101000, out);
            $finish;
        end
        arg_0 = 8'b10101000;
        #0;
        if (12'b000010101001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 168", 12'b000010101001, out);
            $finish;
        end
        arg_0 = 8'b10101001;
        #0;
        if (12'b000010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 169", 12'b000010101010, out);
            $finish;
        end
        arg_0 = 8'b10101010;
        #0;
        if (12'b000010101011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 170", 12'b000010101011, out);
            $finish;
        end
        arg_0 = 8'b10101011;
        #0;
        if (12'b000010101100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 171", 12'b000010101100, out);
            $finish;
        end
        arg_0 = 8'b10101100;
        #0;
        if (12'b000010101101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 172", 12'b000010101101, out);
            $finish;
        end
        arg_0 = 8'b10101101;
        #0;
        if (12'b000010101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 173", 12'b000010101110, out);
            $finish;
        end
        arg_0 = 8'b10101110;
        #0;
        if (12'b000010101111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 174", 12'b000010101111, out);
            $finish;
        end
        arg_0 = 8'b10101111;
        #0;
        if (12'b000010110000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 175", 12'b000010110000, out);
            $finish;
        end
        arg_0 = 8'b10110000;
        #0;
        if (12'b000010110001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 176", 12'b000010110001, out);
            $finish;
        end
        arg_0 = 8'b10110001;
        #0;
        if (12'b000010110010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 177", 12'b000010110010, out);
            $finish;
        end
        arg_0 = 8'b10110010;
        #0;
        if (12'b000010110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 178", 12'b000010110011, out);
            $finish;
        end
        arg_0 = 8'b10110011;
        #0;
        if (12'b000010110100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 179", 12'b000010110100, out);
            $finish;
        end
        arg_0 = 8'b10110100;
        #0;
        if (12'b000010110101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 180", 12'b000010110101, out);
            $finish;
        end
        arg_0 = 8'b10110101;
        #0;
        if (12'b000010110110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 181", 12'b000010110110, out);
            $finish;
        end
        arg_0 = 8'b10110110;
        #0;
        if (12'b000010110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 182", 12'b000010110111, out);
            $finish;
        end
        arg_0 = 8'b10110111;
        #0;
        if (12'b000010111000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 183", 12'b000010111000, out);
            $finish;
        end
        arg_0 = 8'b10111000;
        #0;
        if (12'b000010111001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 184", 12'b000010111001, out);
            $finish;
        end
        arg_0 = 8'b10111001;
        #0;
        if (12'b000010111010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 185", 12'b000010111010, out);
            $finish;
        end
        arg_0 = 8'b10111010;
        #0;
        if (12'b000010111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 186", 12'b000010111011, out);
            $finish;
        end
        arg_0 = 8'b10111011;
        #0;
        if (12'b000010111100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 187", 12'b000010111100, out);
            $finish;
        end
        arg_0 = 8'b10111100;
        #0;
        if (12'b000010111101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 188", 12'b000010111101, out);
            $finish;
        end
        arg_0 = 8'b10111101;
        #0;
        if (12'b000010111110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 189", 12'b000010111110, out);
            $finish;
        end
        arg_0 = 8'b10111110;
        #0;
        if (12'b000010111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 190", 12'b000010111111, out);
            $finish;
        end
        arg_0 = 8'b10111111;
        #0;
        if (12'b000011000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 191", 12'b000011000000, out);
            $finish;
        end
        arg_0 = 8'b11000000;
        #0;
        if (12'b000011000001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 192", 12'b000011000001, out);
            $finish;
        end
        arg_0 = 8'b11000001;
        #0;
        if (12'b000011000010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 193", 12'b000011000010, out);
            $finish;
        end
        arg_0 = 8'b11000010;
        #0;
        if (12'b000011000011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 194", 12'b000011000011, out);
            $finish;
        end
        arg_0 = 8'b11000011;
        #0;
        if (12'b000011000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 195", 12'b000011000100, out);
            $finish;
        end
        arg_0 = 8'b11000100;
        #0;
        if (12'b000011000101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 196", 12'b000011000101, out);
            $finish;
        end
        arg_0 = 8'b11000101;
        #0;
        if (12'b000011000110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 197", 12'b000011000110, out);
            $finish;
        end
        arg_0 = 8'b11000110;
        #0;
        if (12'b000011000111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 198", 12'b000011000111, out);
            $finish;
        end
        arg_0 = 8'b11000111;
        #0;
        if (12'b000011001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 199", 12'b000011001000, out);
            $finish;
        end
        arg_0 = 8'b11001000;
        #0;
        if (12'b000011001001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 200", 12'b000011001001, out);
            $finish;
        end
        arg_0 = 8'b11001001;
        #0;
        if (12'b000011001010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 201", 12'b000011001010, out);
            $finish;
        end
        arg_0 = 8'b11001010;
        #0;
        if (12'b000011001011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 202", 12'b000011001011, out);
            $finish;
        end
        arg_0 = 8'b11001011;
        #0;
        if (12'b000011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 203", 12'b000011001100, out);
            $finish;
        end
        arg_0 = 8'b11001100;
        #0;
        if (12'b000011001101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 204", 12'b000011001101, out);
            $finish;
        end
        arg_0 = 8'b11001101;
        #0;
        if (12'b000011001110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 205", 12'b000011001110, out);
            $finish;
        end
        arg_0 = 8'b11001110;
        #0;
        if (12'b000011001111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 206", 12'b000011001111, out);
            $finish;
        end
        arg_0 = 8'b11001111;
        #0;
        if (12'b000011010000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 207", 12'b000011010000, out);
            $finish;
        end
        arg_0 = 8'b11010000;
        #0;
        if (12'b000011010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 208", 12'b000011010001, out);
            $finish;
        end
        arg_0 = 8'b11010001;
        #0;
        if (12'b000011010010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 209", 12'b000011010010, out);
            $finish;
        end
        arg_0 = 8'b11010010;
        #0;
        if (12'b000011010011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 210", 12'b000011010011, out);
            $finish;
        end
        arg_0 = 8'b11010011;
        #0;
        if (12'b000011010100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 211", 12'b000011010100, out);
            $finish;
        end
        arg_0 = 8'b11010100;
        #0;
        if (12'b000011010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 212", 12'b000011010101, out);
            $finish;
        end
        arg_0 = 8'b11010101;
        #0;
        if (12'b000011010110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 213", 12'b000011010110, out);
            $finish;
        end
        arg_0 = 8'b11010110;
        #0;
        if (12'b000011010111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 214", 12'b000011010111, out);
            $finish;
        end
        arg_0 = 8'b11010111;
        #0;
        if (12'b000011011000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 215", 12'b000011011000, out);
            $finish;
        end
        arg_0 = 8'b11011000;
        #0;
        if (12'b000011011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 216", 12'b000011011001, out);
            $finish;
        end
        arg_0 = 8'b11011001;
        #0;
        if (12'b000011011010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 217", 12'b000011011010, out);
            $finish;
        end
        arg_0 = 8'b11011010;
        #0;
        if (12'b000011011011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 218", 12'b000011011011, out);
            $finish;
        end
        arg_0 = 8'b11011011;
        #0;
        if (12'b000011011100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 219", 12'b000011011100, out);
            $finish;
        end
        arg_0 = 8'b11011100;
        #0;
        if (12'b000011011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 220", 12'b000011011101, out);
            $finish;
        end
        arg_0 = 8'b11011101;
        #0;
        if (12'b000011011110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 221", 12'b000011011110, out);
            $finish;
        end
        arg_0 = 8'b11011110;
        #0;
        if (12'b000011011111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 222", 12'b000011011111, out);
            $finish;
        end
        arg_0 = 8'b11011111;
        #0;
        if (12'b000011100000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 223", 12'b000011100000, out);
            $finish;
        end
        arg_0 = 8'b11100000;
        #0;
        if (12'b000011100001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 224", 12'b000011100001, out);
            $finish;
        end
        arg_0 = 8'b11100001;
        #0;
        if (12'b000011100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 225", 12'b000011100010, out);
            $finish;
        end
        arg_0 = 8'b11100010;
        #0;
        if (12'b000011100011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 226", 12'b000011100011, out);
            $finish;
        end
        arg_0 = 8'b11100011;
        #0;
        if (12'b000011100100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 227", 12'b000011100100, out);
            $finish;
        end
        arg_0 = 8'b11100100;
        #0;
        if (12'b000011100101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 228", 12'b000011100101, out);
            $finish;
        end
        arg_0 = 8'b11100101;
        #0;
        if (12'b000011100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 229", 12'b000011100110, out);
            $finish;
        end
        arg_0 = 8'b11100110;
        #0;
        if (12'b000011100111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 230", 12'b000011100111, out);
            $finish;
        end
        arg_0 = 8'b11100111;
        #0;
        if (12'b000011101000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 231", 12'b000011101000, out);
            $finish;
        end
        arg_0 = 8'b11101000;
        #0;
        if (12'b000011101001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 232", 12'b000011101001, out);
            $finish;
        end
        arg_0 = 8'b11101001;
        #0;
        if (12'b000011101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 233", 12'b000011101010, out);
            $finish;
        end
        arg_0 = 8'b11101010;
        #0;
        if (12'b000011101011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 234", 12'b000011101011, out);
            $finish;
        end
        arg_0 = 8'b11101011;
        #0;
        if (12'b000011101100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 235", 12'b000011101100, out);
            $finish;
        end
        arg_0 = 8'b11101100;
        #0;
        if (12'b000011101101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 236", 12'b000011101101, out);
            $finish;
        end
        arg_0 = 8'b11101101;
        #0;
        if (12'b000011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 237", 12'b000011101110, out);
            $finish;
        end
        arg_0 = 8'b11101110;
        #0;
        if (12'b000011101111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 238", 12'b000011101111, out);
            $finish;
        end
        arg_0 = 8'b11101111;
        #0;
        if (12'b000011110000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 239", 12'b000011110000, out);
            $finish;
        end
        arg_0 = 8'b11110000;
        #0;
        if (12'b000011110001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 240", 12'b000011110001, out);
            $finish;
        end
        arg_0 = 8'b11110001;
        #0;
        if (12'b000011110010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 241", 12'b000011110010, out);
            $finish;
        end
        arg_0 = 8'b11110010;
        #0;
        if (12'b000011110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 242", 12'b000011110011, out);
            $finish;
        end
        arg_0 = 8'b11110011;
        #0;
        if (12'b000011110100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 243", 12'b000011110100, out);
            $finish;
        end
        arg_0 = 8'b11110100;
        #0;
        if (12'b000011110101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 244", 12'b000011110101, out);
            $finish;
        end
        arg_0 = 8'b11110101;
        #0;
        if (12'b000011110110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 245", 12'b000011110110, out);
            $finish;
        end
        arg_0 = 8'b11110110;
        #0;
        if (12'b000011110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 246", 12'b000011110111, out);
            $finish;
        end
        arg_0 = 8'b11110111;
        #0;
        if (12'b000011111000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 247", 12'b000011111000, out);
            $finish;
        end
        arg_0 = 8'b11111000;
        #0;
        if (12'b000011111001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 248", 12'b000011111001, out);
            $finish;
        end
        arg_0 = 8'b11111001;
        #0;
        if (12'b000011111010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 249", 12'b000011111010, out);
            $finish;
        end
        arg_0 = 8'b11111010;
        #0;
        if (12'b000011111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 250", 12'b000011111011, out);
            $finish;
        end
        arg_0 = 8'b11111011;
        #0;
        if (12'b000011111100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 251", 12'b000011111100, out);
            $finish;
        end
        arg_0 = 8'b11111100;
        #0;
        if (12'b000011111101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 252", 12'b000011111101, out);
            $finish;
        end
        arg_0 = 8'b11111101;
        #0;
        if (12'b000011111110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 253", 12'b000011111110, out);
            $finish;
        end
        arg_0 = 8'b11111110;
        #0;
        if (12'b000011111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 254", 12'b000011111111, out);
            $finish;
        end
        arg_0 = 8'b11111111;
        #0;
        if (12'b000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 255", 12'b000000000000, out);
            $finish;
        end
        $display("TESTBENCH OK", );
        $finish;
    end
    function [11:0] kernel_do_stuff(input reg [7:0] arg_0);
        reg [7:0] or0;
        reg [7:0] or1;
        reg [11:0] or2;
        localparam ol0 = 8'b00000001;
        begin
            or0 = arg_0;
            // let a = a.val();
            //
            // let b = a + 1;
            //
            or1 = or0 + ol0;
            // let c = b.resize();
            //
            or2 = { {4{1'b0}}, or1 };
            // signal(c)
            //
            kernel_do_stuff = or2;
        end
    endfunction
endmodule
