// Autogenerated testbench for kernel_do_stuff
module testbench();
    wire [5:0] out;
    reg [7:0] arg_0;
    assign out = kernel_do_stuff(arg_0);
    initial begin
        arg_0 = 8'sb00000000;
        #0;
        if (6'sb000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 0", 6'sb000000, out);
            $finish;
        end
        arg_0 = 8'sb00000001;
        #0;
        if (6'sb000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 1", 6'sb000000, out);
            $finish;
        end
        arg_0 = 8'sb00000010;
        #0;
        if (6'sb000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 2", 6'sb000000, out);
            $finish;
        end
        arg_0 = 8'sb00000011;
        #0;
        if (6'sb000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 3", 6'sb000000, out);
            $finish;
        end
        arg_0 = 8'sb00000100;
        #0;
        if (6'sb000001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 4", 6'sb000001, out);
            $finish;
        end
        arg_0 = 8'sb00000101;
        #0;
        if (6'sb000001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 5", 6'sb000001, out);
            $finish;
        end
        arg_0 = 8'sb00000110;
        #0;
        if (6'sb000001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 6", 6'sb000001, out);
            $finish;
        end
        arg_0 = 8'sb00000111;
        #0;
        if (6'sb000001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 7", 6'sb000001, out);
            $finish;
        end
        arg_0 = 8'sb00001000;
        #0;
        if (6'sb000010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 8", 6'sb000010, out);
            $finish;
        end
        arg_0 = 8'sb00001001;
        #0;
        if (6'sb000010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 9", 6'sb000010, out);
            $finish;
        end
        arg_0 = 8'sb00001010;
        #0;
        if (6'sb000010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 10", 6'sb000010, out);
            $finish;
        end
        arg_0 = 8'sb00001011;
        #0;
        if (6'sb000010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 11", 6'sb000010, out);
            $finish;
        end
        arg_0 = 8'sb00001100;
        #0;
        if (6'sb000011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 12", 6'sb000011, out);
            $finish;
        end
        arg_0 = 8'sb00001101;
        #0;
        if (6'sb000011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 13", 6'sb000011, out);
            $finish;
        end
        arg_0 = 8'sb00001110;
        #0;
        if (6'sb000011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 14", 6'sb000011, out);
            $finish;
        end
        arg_0 = 8'sb00001111;
        #0;
        if (6'sb000011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 15", 6'sb000011, out);
            $finish;
        end
        arg_0 = 8'sb00010000;
        #0;
        if (6'sb000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 16", 6'sb000100, out);
            $finish;
        end
        arg_0 = 8'sb00010001;
        #0;
        if (6'sb000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 17", 6'sb000100, out);
            $finish;
        end
        arg_0 = 8'sb00010010;
        #0;
        if (6'sb000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 18", 6'sb000100, out);
            $finish;
        end
        arg_0 = 8'sb00010011;
        #0;
        if (6'sb000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 19", 6'sb000100, out);
            $finish;
        end
        arg_0 = 8'sb00010100;
        #0;
        if (6'sb000101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 20", 6'sb000101, out);
            $finish;
        end
        arg_0 = 8'sb00010101;
        #0;
        if (6'sb000101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 21", 6'sb000101, out);
            $finish;
        end
        arg_0 = 8'sb00010110;
        #0;
        if (6'sb000101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 22", 6'sb000101, out);
            $finish;
        end
        arg_0 = 8'sb00010111;
        #0;
        if (6'sb000101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 23", 6'sb000101, out);
            $finish;
        end
        arg_0 = 8'sb00011000;
        #0;
        if (6'sb000110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 24", 6'sb000110, out);
            $finish;
        end
        arg_0 = 8'sb00011001;
        #0;
        if (6'sb000110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 25", 6'sb000110, out);
            $finish;
        end
        arg_0 = 8'sb00011010;
        #0;
        if (6'sb000110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 26", 6'sb000110, out);
            $finish;
        end
        arg_0 = 8'sb00011011;
        #0;
        if (6'sb000110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 27", 6'sb000110, out);
            $finish;
        end
        arg_0 = 8'sb00011100;
        #0;
        if (6'sb000111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 28", 6'sb000111, out);
            $finish;
        end
        arg_0 = 8'sb00011101;
        #0;
        if (6'sb000111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 29", 6'sb000111, out);
            $finish;
        end
        arg_0 = 8'sb00011110;
        #0;
        if (6'sb000111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 30", 6'sb000111, out);
            $finish;
        end
        arg_0 = 8'sb00011111;
        #0;
        if (6'sb000111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 31", 6'sb000111, out);
            $finish;
        end
        arg_0 = 8'sb00100000;
        #0;
        if (6'sb001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 32", 6'sb001000, out);
            $finish;
        end
        arg_0 = 8'sb00100001;
        #0;
        if (6'sb001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 33", 6'sb001000, out);
            $finish;
        end
        arg_0 = 8'sb00100010;
        #0;
        if (6'sb001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 34", 6'sb001000, out);
            $finish;
        end
        arg_0 = 8'sb00100011;
        #0;
        if (6'sb001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 35", 6'sb001000, out);
            $finish;
        end
        arg_0 = 8'sb00100100;
        #0;
        if (6'sb001001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 36", 6'sb001001, out);
            $finish;
        end
        arg_0 = 8'sb00100101;
        #0;
        if (6'sb001001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 37", 6'sb001001, out);
            $finish;
        end
        arg_0 = 8'sb00100110;
        #0;
        if (6'sb001001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 38", 6'sb001001, out);
            $finish;
        end
        arg_0 = 8'sb00100111;
        #0;
        if (6'sb001001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 39", 6'sb001001, out);
            $finish;
        end
        arg_0 = 8'sb00101000;
        #0;
        if (6'sb001010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 40", 6'sb001010, out);
            $finish;
        end
        arg_0 = 8'sb00101001;
        #0;
        if (6'sb001010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 41", 6'sb001010, out);
            $finish;
        end
        arg_0 = 8'sb00101010;
        #0;
        if (6'sb001010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 42", 6'sb001010, out);
            $finish;
        end
        arg_0 = 8'sb00101011;
        #0;
        if (6'sb001010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 43", 6'sb001010, out);
            $finish;
        end
        arg_0 = 8'sb00101100;
        #0;
        if (6'sb001011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 44", 6'sb001011, out);
            $finish;
        end
        arg_0 = 8'sb00101101;
        #0;
        if (6'sb001011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 45", 6'sb001011, out);
            $finish;
        end
        arg_0 = 8'sb00101110;
        #0;
        if (6'sb001011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 46", 6'sb001011, out);
            $finish;
        end
        arg_0 = 8'sb00101111;
        #0;
        if (6'sb001011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 47", 6'sb001011, out);
            $finish;
        end
        arg_0 = 8'sb00110000;
        #0;
        if (6'sb001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 48", 6'sb001100, out);
            $finish;
        end
        arg_0 = 8'sb00110001;
        #0;
        if (6'sb001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 49", 6'sb001100, out);
            $finish;
        end
        arg_0 = 8'sb00110010;
        #0;
        if (6'sb001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 50", 6'sb001100, out);
            $finish;
        end
        arg_0 = 8'sb00110011;
        #0;
        if (6'sb001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 51", 6'sb001100, out);
            $finish;
        end
        arg_0 = 8'sb00110100;
        #0;
        if (6'sb001101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 52", 6'sb001101, out);
            $finish;
        end
        arg_0 = 8'sb00110101;
        #0;
        if (6'sb001101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 53", 6'sb001101, out);
            $finish;
        end
        arg_0 = 8'sb00110110;
        #0;
        if (6'sb001101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 54", 6'sb001101, out);
            $finish;
        end
        arg_0 = 8'sb00110111;
        #0;
        if (6'sb001101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 55", 6'sb001101, out);
            $finish;
        end
        arg_0 = 8'sb00111000;
        #0;
        if (6'sb001110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 56", 6'sb001110, out);
            $finish;
        end
        arg_0 = 8'sb00111001;
        #0;
        if (6'sb001110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 57", 6'sb001110, out);
            $finish;
        end
        arg_0 = 8'sb00111010;
        #0;
        if (6'sb001110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 58", 6'sb001110, out);
            $finish;
        end
        arg_0 = 8'sb00111011;
        #0;
        if (6'sb001110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 59", 6'sb001110, out);
            $finish;
        end
        arg_0 = 8'sb00111100;
        #0;
        if (6'sb001111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 60", 6'sb001111, out);
            $finish;
        end
        arg_0 = 8'sb00111101;
        #0;
        if (6'sb001111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 61", 6'sb001111, out);
            $finish;
        end
        arg_0 = 8'sb00111110;
        #0;
        if (6'sb001111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 62", 6'sb001111, out);
            $finish;
        end
        arg_0 = 8'sb00111111;
        #0;
        if (6'sb001111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 63", 6'sb001111, out);
            $finish;
        end
        arg_0 = 8'sb01000000;
        #0;
        if (6'sb010000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 64", 6'sb010000, out);
            $finish;
        end
        arg_0 = 8'sb01000001;
        #0;
        if (6'sb010000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 65", 6'sb010000, out);
            $finish;
        end
        arg_0 = 8'sb01000010;
        #0;
        if (6'sb010000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 66", 6'sb010000, out);
            $finish;
        end
        arg_0 = 8'sb01000011;
        #0;
        if (6'sb010000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 67", 6'sb010000, out);
            $finish;
        end
        arg_0 = 8'sb01000100;
        #0;
        if (6'sb010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 68", 6'sb010001, out);
            $finish;
        end
        arg_0 = 8'sb01000101;
        #0;
        if (6'sb010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 69", 6'sb010001, out);
            $finish;
        end
        arg_0 = 8'sb01000110;
        #0;
        if (6'sb010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 70", 6'sb010001, out);
            $finish;
        end
        arg_0 = 8'sb01000111;
        #0;
        if (6'sb010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 71", 6'sb010001, out);
            $finish;
        end
        arg_0 = 8'sb01001000;
        #0;
        if (6'sb010010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 72", 6'sb010010, out);
            $finish;
        end
        arg_0 = 8'sb01001001;
        #0;
        if (6'sb010010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 73", 6'sb010010, out);
            $finish;
        end
        arg_0 = 8'sb01001010;
        #0;
        if (6'sb010010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 74", 6'sb010010, out);
            $finish;
        end
        arg_0 = 8'sb01001011;
        #0;
        if (6'sb010010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 75", 6'sb010010, out);
            $finish;
        end
        arg_0 = 8'sb01001100;
        #0;
        if (6'sb010011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 76", 6'sb010011, out);
            $finish;
        end
        arg_0 = 8'sb01001101;
        #0;
        if (6'sb010011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 77", 6'sb010011, out);
            $finish;
        end
        arg_0 = 8'sb01001110;
        #0;
        if (6'sb010011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 78", 6'sb010011, out);
            $finish;
        end
        arg_0 = 8'sb01001111;
        #0;
        if (6'sb010011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 79", 6'sb010011, out);
            $finish;
        end
        arg_0 = 8'sb01010000;
        #0;
        if (6'sb010100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 80", 6'sb010100, out);
            $finish;
        end
        arg_0 = 8'sb01010001;
        #0;
        if (6'sb010100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 81", 6'sb010100, out);
            $finish;
        end
        arg_0 = 8'sb01010010;
        #0;
        if (6'sb010100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 82", 6'sb010100, out);
            $finish;
        end
        arg_0 = 8'sb01010011;
        #0;
        if (6'sb010100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 83", 6'sb010100, out);
            $finish;
        end
        arg_0 = 8'sb01010100;
        #0;
        if (6'sb010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 84", 6'sb010101, out);
            $finish;
        end
        arg_0 = 8'sb01010101;
        #0;
        if (6'sb010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 85", 6'sb010101, out);
            $finish;
        end
        arg_0 = 8'sb01010110;
        #0;
        if (6'sb010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 86", 6'sb010101, out);
            $finish;
        end
        arg_0 = 8'sb01010111;
        #0;
        if (6'sb010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 87", 6'sb010101, out);
            $finish;
        end
        arg_0 = 8'sb01011000;
        #0;
        if (6'sb010110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 88", 6'sb010110, out);
            $finish;
        end
        arg_0 = 8'sb01011001;
        #0;
        if (6'sb010110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 89", 6'sb010110, out);
            $finish;
        end
        arg_0 = 8'sb01011010;
        #0;
        if (6'sb010110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 90", 6'sb010110, out);
            $finish;
        end
        arg_0 = 8'sb01011011;
        #0;
        if (6'sb010110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 91", 6'sb010110, out);
            $finish;
        end
        arg_0 = 8'sb01011100;
        #0;
        if (6'sb010111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 92", 6'sb010111, out);
            $finish;
        end
        arg_0 = 8'sb01011101;
        #0;
        if (6'sb010111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 93", 6'sb010111, out);
            $finish;
        end
        arg_0 = 8'sb01011110;
        #0;
        if (6'sb010111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 94", 6'sb010111, out);
            $finish;
        end
        arg_0 = 8'sb01011111;
        #0;
        if (6'sb010111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 95", 6'sb010111, out);
            $finish;
        end
        arg_0 = 8'sb01100000;
        #0;
        if (6'sb011000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 96", 6'sb011000, out);
            $finish;
        end
        arg_0 = 8'sb01100001;
        #0;
        if (6'sb011000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 97", 6'sb011000, out);
            $finish;
        end
        arg_0 = 8'sb01100010;
        #0;
        if (6'sb011000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 98", 6'sb011000, out);
            $finish;
        end
        arg_0 = 8'sb01100011;
        #0;
        if (6'sb011000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 99", 6'sb011000, out);
            $finish;
        end
        arg_0 = 8'sb01100100;
        #0;
        if (6'sb011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 100", 6'sb011001, out);
            $finish;
        end
        arg_0 = 8'sb01100101;
        #0;
        if (6'sb011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 101", 6'sb011001, out);
            $finish;
        end
        arg_0 = 8'sb01100110;
        #0;
        if (6'sb011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 102", 6'sb011001, out);
            $finish;
        end
        arg_0 = 8'sb01100111;
        #0;
        if (6'sb011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 103", 6'sb011001, out);
            $finish;
        end
        arg_0 = 8'sb01101000;
        #0;
        if (6'sb011010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 104", 6'sb011010, out);
            $finish;
        end
        arg_0 = 8'sb01101001;
        #0;
        if (6'sb011010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 105", 6'sb011010, out);
            $finish;
        end
        arg_0 = 8'sb01101010;
        #0;
        if (6'sb011010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 106", 6'sb011010, out);
            $finish;
        end
        arg_0 = 8'sb01101011;
        #0;
        if (6'sb011010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 107", 6'sb011010, out);
            $finish;
        end
        arg_0 = 8'sb01101100;
        #0;
        if (6'sb011011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 108", 6'sb011011, out);
            $finish;
        end
        arg_0 = 8'sb01101101;
        #0;
        if (6'sb011011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 109", 6'sb011011, out);
            $finish;
        end
        arg_0 = 8'sb01101110;
        #0;
        if (6'sb011011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 110", 6'sb011011, out);
            $finish;
        end
        arg_0 = 8'sb01101111;
        #0;
        if (6'sb011011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 111", 6'sb011011, out);
            $finish;
        end
        arg_0 = 8'sb01110000;
        #0;
        if (6'sb011100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 112", 6'sb011100, out);
            $finish;
        end
        arg_0 = 8'sb01110001;
        #0;
        if (6'sb011100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 113", 6'sb011100, out);
            $finish;
        end
        arg_0 = 8'sb01110010;
        #0;
        if (6'sb011100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 114", 6'sb011100, out);
            $finish;
        end
        arg_0 = 8'sb01110011;
        #0;
        if (6'sb011100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 115", 6'sb011100, out);
            $finish;
        end
        arg_0 = 8'sb01110100;
        #0;
        if (6'sb011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 116", 6'sb011101, out);
            $finish;
        end
        arg_0 = 8'sb01110101;
        #0;
        if (6'sb011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 117", 6'sb011101, out);
            $finish;
        end
        arg_0 = 8'sb01110110;
        #0;
        if (6'sb011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 118", 6'sb011101, out);
            $finish;
        end
        arg_0 = 8'sb01110111;
        #0;
        if (6'sb011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 119", 6'sb011101, out);
            $finish;
        end
        arg_0 = 8'sb01111000;
        #0;
        if (6'sb011110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 120", 6'sb011110, out);
            $finish;
        end
        arg_0 = 8'sb01111001;
        #0;
        if (6'sb011110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 121", 6'sb011110, out);
            $finish;
        end
        arg_0 = 8'sb01111010;
        #0;
        if (6'sb011110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 122", 6'sb011110, out);
            $finish;
        end
        arg_0 = 8'sb01111011;
        #0;
        if (6'sb011110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 123", 6'sb011110, out);
            $finish;
        end
        arg_0 = 8'sb01111100;
        #0;
        if (6'sb011111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 124", 6'sb011111, out);
            $finish;
        end
        arg_0 = 8'sb01111101;
        #0;
        if (6'sb011111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 125", 6'sb011111, out);
            $finish;
        end
        arg_0 = 8'sb01111110;
        #0;
        if (6'sb011111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 126", 6'sb011111, out);
            $finish;
        end
        arg_0 = 8'sb01111111;
        #0;
        if (6'sb011111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 127", 6'sb011111, out);
            $finish;
        end
        arg_0 = 8'sb10000000;
        #0;
        if (6'sb100000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 128", 6'sb100000, out);
            $finish;
        end
        arg_0 = 8'sb10000001;
        #0;
        if (6'sb100000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 129", 6'sb100000, out);
            $finish;
        end
        arg_0 = 8'sb10000010;
        #0;
        if (6'sb100000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 130", 6'sb100000, out);
            $finish;
        end
        arg_0 = 8'sb10000011;
        #0;
        if (6'sb100000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 131", 6'sb100000, out);
            $finish;
        end
        arg_0 = 8'sb10000100;
        #0;
        if (6'sb100001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 132", 6'sb100001, out);
            $finish;
        end
        arg_0 = 8'sb10000101;
        #0;
        if (6'sb100001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 133", 6'sb100001, out);
            $finish;
        end
        arg_0 = 8'sb10000110;
        #0;
        if (6'sb100001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 134", 6'sb100001, out);
            $finish;
        end
        arg_0 = 8'sb10000111;
        #0;
        if (6'sb100001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 135", 6'sb100001, out);
            $finish;
        end
        arg_0 = 8'sb10001000;
        #0;
        if (6'sb100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 136", 6'sb100010, out);
            $finish;
        end
        arg_0 = 8'sb10001001;
        #0;
        if (6'sb100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 137", 6'sb100010, out);
            $finish;
        end
        arg_0 = 8'sb10001010;
        #0;
        if (6'sb100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 138", 6'sb100010, out);
            $finish;
        end
        arg_0 = 8'sb10001011;
        #0;
        if (6'sb100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 139", 6'sb100010, out);
            $finish;
        end
        arg_0 = 8'sb10001100;
        #0;
        if (6'sb100011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 140", 6'sb100011, out);
            $finish;
        end
        arg_0 = 8'sb10001101;
        #0;
        if (6'sb100011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 141", 6'sb100011, out);
            $finish;
        end
        arg_0 = 8'sb10001110;
        #0;
        if (6'sb100011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 142", 6'sb100011, out);
            $finish;
        end
        arg_0 = 8'sb10001111;
        #0;
        if (6'sb100011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 143", 6'sb100011, out);
            $finish;
        end
        arg_0 = 8'sb10010000;
        #0;
        if (6'sb100100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 144", 6'sb100100, out);
            $finish;
        end
        arg_0 = 8'sb10010001;
        #0;
        if (6'sb100100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 145", 6'sb100100, out);
            $finish;
        end
        arg_0 = 8'sb10010010;
        #0;
        if (6'sb100100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 146", 6'sb100100, out);
            $finish;
        end
        arg_0 = 8'sb10010011;
        #0;
        if (6'sb100100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 147", 6'sb100100, out);
            $finish;
        end
        arg_0 = 8'sb10010100;
        #0;
        if (6'sb100101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 148", 6'sb100101, out);
            $finish;
        end
        arg_0 = 8'sb10010101;
        #0;
        if (6'sb100101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 149", 6'sb100101, out);
            $finish;
        end
        arg_0 = 8'sb10010110;
        #0;
        if (6'sb100101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 150", 6'sb100101, out);
            $finish;
        end
        arg_0 = 8'sb10010111;
        #0;
        if (6'sb100101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 151", 6'sb100101, out);
            $finish;
        end
        arg_0 = 8'sb10011000;
        #0;
        if (6'sb100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 152", 6'sb100110, out);
            $finish;
        end
        arg_0 = 8'sb10011001;
        #0;
        if (6'sb100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 153", 6'sb100110, out);
            $finish;
        end
        arg_0 = 8'sb10011010;
        #0;
        if (6'sb100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 154", 6'sb100110, out);
            $finish;
        end
        arg_0 = 8'sb10011011;
        #0;
        if (6'sb100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 155", 6'sb100110, out);
            $finish;
        end
        arg_0 = 8'sb10011100;
        #0;
        if (6'sb100111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 156", 6'sb100111, out);
            $finish;
        end
        arg_0 = 8'sb10011101;
        #0;
        if (6'sb100111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 157", 6'sb100111, out);
            $finish;
        end
        arg_0 = 8'sb10011110;
        #0;
        if (6'sb100111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 158", 6'sb100111, out);
            $finish;
        end
        arg_0 = 8'sb10011111;
        #0;
        if (6'sb100111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 159", 6'sb100111, out);
            $finish;
        end
        arg_0 = 8'sb10100000;
        #0;
        if (6'sb101000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 160", 6'sb101000, out);
            $finish;
        end
        arg_0 = 8'sb10100001;
        #0;
        if (6'sb101000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 161", 6'sb101000, out);
            $finish;
        end
        arg_0 = 8'sb10100010;
        #0;
        if (6'sb101000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 162", 6'sb101000, out);
            $finish;
        end
        arg_0 = 8'sb10100011;
        #0;
        if (6'sb101000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 163", 6'sb101000, out);
            $finish;
        end
        arg_0 = 8'sb10100100;
        #0;
        if (6'sb101001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 164", 6'sb101001, out);
            $finish;
        end
        arg_0 = 8'sb10100101;
        #0;
        if (6'sb101001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 165", 6'sb101001, out);
            $finish;
        end
        arg_0 = 8'sb10100110;
        #0;
        if (6'sb101001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 166", 6'sb101001, out);
            $finish;
        end
        arg_0 = 8'sb10100111;
        #0;
        if (6'sb101001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 167", 6'sb101001, out);
            $finish;
        end
        arg_0 = 8'sb10101000;
        #0;
        if (6'sb101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 168", 6'sb101010, out);
            $finish;
        end
        arg_0 = 8'sb10101001;
        #0;
        if (6'sb101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 169", 6'sb101010, out);
            $finish;
        end
        arg_0 = 8'sb10101010;
        #0;
        if (6'sb101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 170", 6'sb101010, out);
            $finish;
        end
        arg_0 = 8'sb10101011;
        #0;
        if (6'sb101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 171", 6'sb101010, out);
            $finish;
        end
        arg_0 = 8'sb10101100;
        #0;
        if (6'sb101011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 172", 6'sb101011, out);
            $finish;
        end
        arg_0 = 8'sb10101101;
        #0;
        if (6'sb101011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 173", 6'sb101011, out);
            $finish;
        end
        arg_0 = 8'sb10101110;
        #0;
        if (6'sb101011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 174", 6'sb101011, out);
            $finish;
        end
        arg_0 = 8'sb10101111;
        #0;
        if (6'sb101011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 175", 6'sb101011, out);
            $finish;
        end
        arg_0 = 8'sb10110000;
        #0;
        if (6'sb101100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 176", 6'sb101100, out);
            $finish;
        end
        arg_0 = 8'sb10110001;
        #0;
        if (6'sb101100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 177", 6'sb101100, out);
            $finish;
        end
        arg_0 = 8'sb10110010;
        #0;
        if (6'sb101100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 178", 6'sb101100, out);
            $finish;
        end
        arg_0 = 8'sb10110011;
        #0;
        if (6'sb101100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 179", 6'sb101100, out);
            $finish;
        end
        arg_0 = 8'sb10110100;
        #0;
        if (6'sb101101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 180", 6'sb101101, out);
            $finish;
        end
        arg_0 = 8'sb10110101;
        #0;
        if (6'sb101101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 181", 6'sb101101, out);
            $finish;
        end
        arg_0 = 8'sb10110110;
        #0;
        if (6'sb101101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 182", 6'sb101101, out);
            $finish;
        end
        arg_0 = 8'sb10110111;
        #0;
        if (6'sb101101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 183", 6'sb101101, out);
            $finish;
        end
        arg_0 = 8'sb10111000;
        #0;
        if (6'sb101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 184", 6'sb101110, out);
            $finish;
        end
        arg_0 = 8'sb10111001;
        #0;
        if (6'sb101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 185", 6'sb101110, out);
            $finish;
        end
        arg_0 = 8'sb10111010;
        #0;
        if (6'sb101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 186", 6'sb101110, out);
            $finish;
        end
        arg_0 = 8'sb10111011;
        #0;
        if (6'sb101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 187", 6'sb101110, out);
            $finish;
        end
        arg_0 = 8'sb10111100;
        #0;
        if (6'sb101111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 188", 6'sb101111, out);
            $finish;
        end
        arg_0 = 8'sb10111101;
        #0;
        if (6'sb101111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 189", 6'sb101111, out);
            $finish;
        end
        arg_0 = 8'sb10111110;
        #0;
        if (6'sb101111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 190", 6'sb101111, out);
            $finish;
        end
        arg_0 = 8'sb10111111;
        #0;
        if (6'sb101111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 191", 6'sb101111, out);
            $finish;
        end
        arg_0 = 8'sb11000000;
        #0;
        if (6'sb110000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 192", 6'sb110000, out);
            $finish;
        end
        arg_0 = 8'sb11000001;
        #0;
        if (6'sb110000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 193", 6'sb110000, out);
            $finish;
        end
        arg_0 = 8'sb11000010;
        #0;
        if (6'sb110000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 194", 6'sb110000, out);
            $finish;
        end
        arg_0 = 8'sb11000011;
        #0;
        if (6'sb110000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 195", 6'sb110000, out);
            $finish;
        end
        arg_0 = 8'sb11000100;
        #0;
        if (6'sb110001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 196", 6'sb110001, out);
            $finish;
        end
        arg_0 = 8'sb11000101;
        #0;
        if (6'sb110001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 197", 6'sb110001, out);
            $finish;
        end
        arg_0 = 8'sb11000110;
        #0;
        if (6'sb110001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 198", 6'sb110001, out);
            $finish;
        end
        arg_0 = 8'sb11000111;
        #0;
        if (6'sb110001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 199", 6'sb110001, out);
            $finish;
        end
        arg_0 = 8'sb11001000;
        #0;
        if (6'sb110010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 200", 6'sb110010, out);
            $finish;
        end
        arg_0 = 8'sb11001001;
        #0;
        if (6'sb110010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 201", 6'sb110010, out);
            $finish;
        end
        arg_0 = 8'sb11001010;
        #0;
        if (6'sb110010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 202", 6'sb110010, out);
            $finish;
        end
        arg_0 = 8'sb11001011;
        #0;
        if (6'sb110010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 203", 6'sb110010, out);
            $finish;
        end
        arg_0 = 8'sb11001100;
        #0;
        if (6'sb110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 204", 6'sb110011, out);
            $finish;
        end
        arg_0 = 8'sb11001101;
        #0;
        if (6'sb110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 205", 6'sb110011, out);
            $finish;
        end
        arg_0 = 8'sb11001110;
        #0;
        if (6'sb110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 206", 6'sb110011, out);
            $finish;
        end
        arg_0 = 8'sb11001111;
        #0;
        if (6'sb110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 207", 6'sb110011, out);
            $finish;
        end
        arg_0 = 8'sb11010000;
        #0;
        if (6'sb110100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 208", 6'sb110100, out);
            $finish;
        end
        arg_0 = 8'sb11010001;
        #0;
        if (6'sb110100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 209", 6'sb110100, out);
            $finish;
        end
        arg_0 = 8'sb11010010;
        #0;
        if (6'sb110100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 210", 6'sb110100, out);
            $finish;
        end
        arg_0 = 8'sb11010011;
        #0;
        if (6'sb110100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 211", 6'sb110100, out);
            $finish;
        end
        arg_0 = 8'sb11010100;
        #0;
        if (6'sb110101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 212", 6'sb110101, out);
            $finish;
        end
        arg_0 = 8'sb11010101;
        #0;
        if (6'sb110101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 213", 6'sb110101, out);
            $finish;
        end
        arg_0 = 8'sb11010110;
        #0;
        if (6'sb110101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 214", 6'sb110101, out);
            $finish;
        end
        arg_0 = 8'sb11010111;
        #0;
        if (6'sb110101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 215", 6'sb110101, out);
            $finish;
        end
        arg_0 = 8'sb11011000;
        #0;
        if (6'sb110110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 216", 6'sb110110, out);
            $finish;
        end
        arg_0 = 8'sb11011001;
        #0;
        if (6'sb110110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 217", 6'sb110110, out);
            $finish;
        end
        arg_0 = 8'sb11011010;
        #0;
        if (6'sb110110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 218", 6'sb110110, out);
            $finish;
        end
        arg_0 = 8'sb11011011;
        #0;
        if (6'sb110110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 219", 6'sb110110, out);
            $finish;
        end
        arg_0 = 8'sb11011100;
        #0;
        if (6'sb110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 220", 6'sb110111, out);
            $finish;
        end
        arg_0 = 8'sb11011101;
        #0;
        if (6'sb110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 221", 6'sb110111, out);
            $finish;
        end
        arg_0 = 8'sb11011110;
        #0;
        if (6'sb110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 222", 6'sb110111, out);
            $finish;
        end
        arg_0 = 8'sb11011111;
        #0;
        if (6'sb110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 223", 6'sb110111, out);
            $finish;
        end
        arg_0 = 8'sb11100000;
        #0;
        if (6'sb111000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 224", 6'sb111000, out);
            $finish;
        end
        arg_0 = 8'sb11100001;
        #0;
        if (6'sb111000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 225", 6'sb111000, out);
            $finish;
        end
        arg_0 = 8'sb11100010;
        #0;
        if (6'sb111000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 226", 6'sb111000, out);
            $finish;
        end
        arg_0 = 8'sb11100011;
        #0;
        if (6'sb111000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 227", 6'sb111000, out);
            $finish;
        end
        arg_0 = 8'sb11100100;
        #0;
        if (6'sb111001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 228", 6'sb111001, out);
            $finish;
        end
        arg_0 = 8'sb11100101;
        #0;
        if (6'sb111001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 229", 6'sb111001, out);
            $finish;
        end
        arg_0 = 8'sb11100110;
        #0;
        if (6'sb111001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 230", 6'sb111001, out);
            $finish;
        end
        arg_0 = 8'sb11100111;
        #0;
        if (6'sb111001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 231", 6'sb111001, out);
            $finish;
        end
        arg_0 = 8'sb11101000;
        #0;
        if (6'sb111010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 232", 6'sb111010, out);
            $finish;
        end
        arg_0 = 8'sb11101001;
        #0;
        if (6'sb111010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 233", 6'sb111010, out);
            $finish;
        end
        arg_0 = 8'sb11101010;
        #0;
        if (6'sb111010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 234", 6'sb111010, out);
            $finish;
        end
        arg_0 = 8'sb11101011;
        #0;
        if (6'sb111010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 235", 6'sb111010, out);
            $finish;
        end
        arg_0 = 8'sb11101100;
        #0;
        if (6'sb111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 236", 6'sb111011, out);
            $finish;
        end
        arg_0 = 8'sb11101101;
        #0;
        if (6'sb111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 237", 6'sb111011, out);
            $finish;
        end
        arg_0 = 8'sb11101110;
        #0;
        if (6'sb111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 238", 6'sb111011, out);
            $finish;
        end
        arg_0 = 8'sb11101111;
        #0;
        if (6'sb111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 239", 6'sb111011, out);
            $finish;
        end
        arg_0 = 8'sb11110000;
        #0;
        if (6'sb111100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 240", 6'sb111100, out);
            $finish;
        end
        arg_0 = 8'sb11110001;
        #0;
        if (6'sb111100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 241", 6'sb111100, out);
            $finish;
        end
        arg_0 = 8'sb11110010;
        #0;
        if (6'sb111100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 242", 6'sb111100, out);
            $finish;
        end
        arg_0 = 8'sb11110011;
        #0;
        if (6'sb111100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 243", 6'sb111100, out);
            $finish;
        end
        arg_0 = 8'sb11110100;
        #0;
        if (6'sb111101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 244", 6'sb111101, out);
            $finish;
        end
        arg_0 = 8'sb11110101;
        #0;
        if (6'sb111101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 245", 6'sb111101, out);
            $finish;
        end
        arg_0 = 8'sb11110110;
        #0;
        if (6'sb111101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 246", 6'sb111101, out);
            $finish;
        end
        arg_0 = 8'sb11110111;
        #0;
        if (6'sb111101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 247", 6'sb111101, out);
            $finish;
        end
        arg_0 = 8'sb11111000;
        #0;
        if (6'sb111110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 248", 6'sb111110, out);
            $finish;
        end
        arg_0 = 8'sb11111001;
        #0;
        if (6'sb111110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 249", 6'sb111110, out);
            $finish;
        end
        arg_0 = 8'sb11111010;
        #0;
        if (6'sb111110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 250", 6'sb111110, out);
            $finish;
        end
        arg_0 = 8'sb11111011;
        #0;
        if (6'sb111110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 251", 6'sb111110, out);
            $finish;
        end
        arg_0 = 8'sb11111100;
        #0;
        if (6'sb111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 252", 6'sb111111, out);
            $finish;
        end
        arg_0 = 8'sb11111101;
        #0;
        if (6'sb111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 253", 6'sb111111, out);
            $finish;
        end
        arg_0 = 8'sb11111110;
        #0;
        if (6'sb111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 254", 6'sb111111, out);
            $finish;
        end
        arg_0 = 8'sb11111111;
        #0;
        if (6'sb111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 255", 6'sb111111, out);
            $finish;
        end
        $display("TESTBENCH OK", );
        $finish;
    end
    function signed [5:0] kernel_do_stuff(input reg signed [7:0] arg_0);
        reg signed [7:0] or0;
        reg signed [5:0] or1;
        reg signed [7:0] or2;
        reg signed [9:0] or3;
        begin
            or0 = arg_0;
            // signal(a.val().xshr())
            //
            or3 = $signed({ {2{or0[7]}}, or0 });
            or2 = or3[9:2];
            or1 = $signed(or2[5:0]);
            kernel_do_stuff = or1;
        end
    endfunction
endmodule
