// Autogenerated testbench for dut
module testbench();
    wire [8:0] out;
    reg [7:0] arg_0;
    dut t (.out(out),.arg_0(arg_0));
    initial begin
        arg_0 = 8'b00000000;
        #0;
        if (9'sb000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 0", 9'sb000000000, out);
            $finish;
        end
        arg_0 = 8'b00000001;
        #0;
        if (9'sb000000001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 1", 9'sb000000001, out);
            $finish;
        end
        arg_0 = 8'b00000010;
        #0;
        if (9'sb000000010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 2", 9'sb000000010, out);
            $finish;
        end
        arg_0 = 8'b00000011;
        #0;
        if (9'sb000000011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 3", 9'sb000000011, out);
            $finish;
        end
        arg_0 = 8'b00000100;
        #0;
        if (9'sb000000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 4", 9'sb000000100, out);
            $finish;
        end
        arg_0 = 8'b00000101;
        #0;
        if (9'sb000000101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 5", 9'sb000000101, out);
            $finish;
        end
        arg_0 = 8'b00000110;
        #0;
        if (9'sb000000110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 6", 9'sb000000110, out);
            $finish;
        end
        arg_0 = 8'b00000111;
        #0;
        if (9'sb000000111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 7", 9'sb000000111, out);
            $finish;
        end
        arg_0 = 8'b00001000;
        #0;
        if (9'sb000001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 8", 9'sb000001000, out);
            $finish;
        end
        arg_0 = 8'b00001001;
        #0;
        if (9'sb000001001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 9", 9'sb000001001, out);
            $finish;
        end
        arg_0 = 8'b00001010;
        #0;
        if (9'sb000001010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 10", 9'sb000001010, out);
            $finish;
        end
        arg_0 = 8'b00001011;
        #0;
        if (9'sb000001011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 11", 9'sb000001011, out);
            $finish;
        end
        arg_0 = 8'b00001100;
        #0;
        if (9'sb000001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 12", 9'sb000001100, out);
            $finish;
        end
        arg_0 = 8'b00001101;
        #0;
        if (9'sb000001101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 13", 9'sb000001101, out);
            $finish;
        end
        arg_0 = 8'b00001110;
        #0;
        if (9'sb000001110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 14", 9'sb000001110, out);
            $finish;
        end
        arg_0 = 8'b00001111;
        #0;
        if (9'sb000001111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 15", 9'sb000001111, out);
            $finish;
        end
        arg_0 = 8'b00010000;
        #0;
        if (9'sb000010000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 16", 9'sb000010000, out);
            $finish;
        end
        arg_0 = 8'b00010001;
        #0;
        if (9'sb000010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 17", 9'sb000010001, out);
            $finish;
        end
        arg_0 = 8'b00010010;
        #0;
        if (9'sb000010010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 18", 9'sb000010010, out);
            $finish;
        end
        arg_0 = 8'b00010011;
        #0;
        if (9'sb000010011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 19", 9'sb000010011, out);
            $finish;
        end
        arg_0 = 8'b00010100;
        #0;
        if (9'sb000010100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 20", 9'sb000010100, out);
            $finish;
        end
        arg_0 = 8'b00010101;
        #0;
        if (9'sb000010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 21", 9'sb000010101, out);
            $finish;
        end
        arg_0 = 8'b00010110;
        #0;
        if (9'sb000010110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 22", 9'sb000010110, out);
            $finish;
        end
        arg_0 = 8'b00010111;
        #0;
        if (9'sb000010111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 23", 9'sb000010111, out);
            $finish;
        end
        arg_0 = 8'b00011000;
        #0;
        if (9'sb000011000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 24", 9'sb000011000, out);
            $finish;
        end
        arg_0 = 8'b00011001;
        #0;
        if (9'sb000011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 25", 9'sb000011001, out);
            $finish;
        end
        arg_0 = 8'b00011010;
        #0;
        if (9'sb000011010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 26", 9'sb000011010, out);
            $finish;
        end
        arg_0 = 8'b00011011;
        #0;
        if (9'sb000011011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 27", 9'sb000011011, out);
            $finish;
        end
        arg_0 = 8'b00011100;
        #0;
        if (9'sb000011100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 28", 9'sb000011100, out);
            $finish;
        end
        arg_0 = 8'b00011101;
        #0;
        if (9'sb000011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 29", 9'sb000011101, out);
            $finish;
        end
        arg_0 = 8'b00011110;
        #0;
        if (9'sb000011110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 30", 9'sb000011110, out);
            $finish;
        end
        arg_0 = 8'b00011111;
        #0;
        if (9'sb000011111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 31", 9'sb000011111, out);
            $finish;
        end
        arg_0 = 8'b00100000;
        #0;
        if (9'sb000100000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 32", 9'sb000100000, out);
            $finish;
        end
        arg_0 = 8'b00100001;
        #0;
        if (9'sb000100001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 33", 9'sb000100001, out);
            $finish;
        end
        arg_0 = 8'b00100010;
        #0;
        if (9'sb000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 34", 9'sb000100010, out);
            $finish;
        end
        arg_0 = 8'b00100011;
        #0;
        if (9'sb000100011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 35", 9'sb000100011, out);
            $finish;
        end
        arg_0 = 8'b00100100;
        #0;
        if (9'sb000100100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 36", 9'sb000100100, out);
            $finish;
        end
        arg_0 = 8'b00100101;
        #0;
        if (9'sb000100101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 37", 9'sb000100101, out);
            $finish;
        end
        arg_0 = 8'b00100110;
        #0;
        if (9'sb000100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 38", 9'sb000100110, out);
            $finish;
        end
        arg_0 = 8'b00100111;
        #0;
        if (9'sb000100111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 39", 9'sb000100111, out);
            $finish;
        end
        arg_0 = 8'b00101000;
        #0;
        if (9'sb000101000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 40", 9'sb000101000, out);
            $finish;
        end
        arg_0 = 8'b00101001;
        #0;
        if (9'sb000101001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 41", 9'sb000101001, out);
            $finish;
        end
        arg_0 = 8'b00101010;
        #0;
        if (9'sb000101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 42", 9'sb000101010, out);
            $finish;
        end
        arg_0 = 8'b00101011;
        #0;
        if (9'sb000101011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 43", 9'sb000101011, out);
            $finish;
        end
        arg_0 = 8'b00101100;
        #0;
        if (9'sb000101100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 44", 9'sb000101100, out);
            $finish;
        end
        arg_0 = 8'b00101101;
        #0;
        if (9'sb000101101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 45", 9'sb000101101, out);
            $finish;
        end
        arg_0 = 8'b00101110;
        #0;
        if (9'sb000101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 46", 9'sb000101110, out);
            $finish;
        end
        arg_0 = 8'b00101111;
        #0;
        if (9'sb000101111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 47", 9'sb000101111, out);
            $finish;
        end
        arg_0 = 8'b00110000;
        #0;
        if (9'sb000110000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 48", 9'sb000110000, out);
            $finish;
        end
        arg_0 = 8'b00110001;
        #0;
        if (9'sb000110001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 49", 9'sb000110001, out);
            $finish;
        end
        arg_0 = 8'b00110010;
        #0;
        if (9'sb000110010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 50", 9'sb000110010, out);
            $finish;
        end
        arg_0 = 8'b00110011;
        #0;
        if (9'sb000110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 51", 9'sb000110011, out);
            $finish;
        end
        arg_0 = 8'b00110100;
        #0;
        if (9'sb000110100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 52", 9'sb000110100, out);
            $finish;
        end
        arg_0 = 8'b00110101;
        #0;
        if (9'sb000110101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 53", 9'sb000110101, out);
            $finish;
        end
        arg_0 = 8'b00110110;
        #0;
        if (9'sb000110110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 54", 9'sb000110110, out);
            $finish;
        end
        arg_0 = 8'b00110111;
        #0;
        if (9'sb000110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 55", 9'sb000110111, out);
            $finish;
        end
        arg_0 = 8'b00111000;
        #0;
        if (9'sb000111000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 56", 9'sb000111000, out);
            $finish;
        end
        arg_0 = 8'b00111001;
        #0;
        if (9'sb000111001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 57", 9'sb000111001, out);
            $finish;
        end
        arg_0 = 8'b00111010;
        #0;
        if (9'sb000111010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 58", 9'sb000111010, out);
            $finish;
        end
        arg_0 = 8'b00111011;
        #0;
        if (9'sb000111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 59", 9'sb000111011, out);
            $finish;
        end
        arg_0 = 8'b00111100;
        #0;
        if (9'sb000111100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 60", 9'sb000111100, out);
            $finish;
        end
        arg_0 = 8'b00111101;
        #0;
        if (9'sb000111101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 61", 9'sb000111101, out);
            $finish;
        end
        arg_0 = 8'b00111110;
        #0;
        if (9'sb000111110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 62", 9'sb000111110, out);
            $finish;
        end
        arg_0 = 8'b00111111;
        #0;
        if (9'sb000111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 63", 9'sb000111111, out);
            $finish;
        end
        arg_0 = 8'b01000000;
        #0;
        if (9'sb001000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 64", 9'sb001000000, out);
            $finish;
        end
        arg_0 = 8'b01000001;
        #0;
        if (9'sb001000001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 65", 9'sb001000001, out);
            $finish;
        end
        arg_0 = 8'b01000010;
        #0;
        if (9'sb001000010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 66", 9'sb001000010, out);
            $finish;
        end
        arg_0 = 8'b01000011;
        #0;
        if (9'sb001000011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 67", 9'sb001000011, out);
            $finish;
        end
        arg_0 = 8'b01000100;
        #0;
        if (9'sb001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 68", 9'sb001000100, out);
            $finish;
        end
        arg_0 = 8'b01000101;
        #0;
        if (9'sb001000101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 69", 9'sb001000101, out);
            $finish;
        end
        arg_0 = 8'b01000110;
        #0;
        if (9'sb001000110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 70", 9'sb001000110, out);
            $finish;
        end
        arg_0 = 8'b01000111;
        #0;
        if (9'sb001000111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 71", 9'sb001000111, out);
            $finish;
        end
        arg_0 = 8'b01001000;
        #0;
        if (9'sb001001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 72", 9'sb001001000, out);
            $finish;
        end
        arg_0 = 8'b01001001;
        #0;
        if (9'sb001001001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 73", 9'sb001001001, out);
            $finish;
        end
        arg_0 = 8'b01001010;
        #0;
        if (9'sb001001010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 74", 9'sb001001010, out);
            $finish;
        end
        arg_0 = 8'b01001011;
        #0;
        if (9'sb001001011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 75", 9'sb001001011, out);
            $finish;
        end
        arg_0 = 8'b01001100;
        #0;
        if (9'sb001001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 76", 9'sb001001100, out);
            $finish;
        end
        arg_0 = 8'b01001101;
        #0;
        if (9'sb001001101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 77", 9'sb001001101, out);
            $finish;
        end
        arg_0 = 8'b01001110;
        #0;
        if (9'sb001001110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 78", 9'sb001001110, out);
            $finish;
        end
        arg_0 = 8'b01001111;
        #0;
        if (9'sb001001111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 79", 9'sb001001111, out);
            $finish;
        end
        arg_0 = 8'b01010000;
        #0;
        if (9'sb001010000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 80", 9'sb001010000, out);
            $finish;
        end
        arg_0 = 8'b01010001;
        #0;
        if (9'sb001010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 81", 9'sb001010001, out);
            $finish;
        end
        arg_0 = 8'b01010010;
        #0;
        if (9'sb001010010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 82", 9'sb001010010, out);
            $finish;
        end
        arg_0 = 8'b01010011;
        #0;
        if (9'sb001010011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 83", 9'sb001010011, out);
            $finish;
        end
        arg_0 = 8'b01010100;
        #0;
        if (9'sb001010100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 84", 9'sb001010100, out);
            $finish;
        end
        arg_0 = 8'b01010101;
        #0;
        if (9'sb001010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 85", 9'sb001010101, out);
            $finish;
        end
        arg_0 = 8'b01010110;
        #0;
        if (9'sb001010110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 86", 9'sb001010110, out);
            $finish;
        end
        arg_0 = 8'b01010111;
        #0;
        if (9'sb001010111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 87", 9'sb001010111, out);
            $finish;
        end
        arg_0 = 8'b01011000;
        #0;
        if (9'sb001011000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 88", 9'sb001011000, out);
            $finish;
        end
        arg_0 = 8'b01011001;
        #0;
        if (9'sb001011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 89", 9'sb001011001, out);
            $finish;
        end
        arg_0 = 8'b01011010;
        #0;
        if (9'sb001011010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 90", 9'sb001011010, out);
            $finish;
        end
        arg_0 = 8'b01011011;
        #0;
        if (9'sb001011011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 91", 9'sb001011011, out);
            $finish;
        end
        arg_0 = 8'b01011100;
        #0;
        if (9'sb001011100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 92", 9'sb001011100, out);
            $finish;
        end
        arg_0 = 8'b01011101;
        #0;
        if (9'sb001011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 93", 9'sb001011101, out);
            $finish;
        end
        arg_0 = 8'b01011110;
        #0;
        if (9'sb001011110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 94", 9'sb001011110, out);
            $finish;
        end
        arg_0 = 8'b01011111;
        #0;
        if (9'sb001011111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 95", 9'sb001011111, out);
            $finish;
        end
        arg_0 = 8'b01100000;
        #0;
        if (9'sb001100000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 96", 9'sb001100000, out);
            $finish;
        end
        arg_0 = 8'b01100001;
        #0;
        if (9'sb001100001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 97", 9'sb001100001, out);
            $finish;
        end
        arg_0 = 8'b01100010;
        #0;
        if (9'sb001100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 98", 9'sb001100010, out);
            $finish;
        end
        arg_0 = 8'b01100011;
        #0;
        if (9'sb001100011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 99", 9'sb001100011, out);
            $finish;
        end
        arg_0 = 8'b01100100;
        #0;
        if (9'sb001100100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 100", 9'sb001100100, out);
            $finish;
        end
        arg_0 = 8'b01100101;
        #0;
        if (9'sb001100101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 101", 9'sb001100101, out);
            $finish;
        end
        arg_0 = 8'b01100110;
        #0;
        if (9'sb001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 102", 9'sb001100110, out);
            $finish;
        end
        arg_0 = 8'b01100111;
        #0;
        if (9'sb001100111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 103", 9'sb001100111, out);
            $finish;
        end
        arg_0 = 8'b01101000;
        #0;
        if (9'sb001101000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 104", 9'sb001101000, out);
            $finish;
        end
        arg_0 = 8'b01101001;
        #0;
        if (9'sb001101001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 105", 9'sb001101001, out);
            $finish;
        end
        arg_0 = 8'b01101010;
        #0;
        if (9'sb001101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 106", 9'sb001101010, out);
            $finish;
        end
        arg_0 = 8'b01101011;
        #0;
        if (9'sb001101011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 107", 9'sb001101011, out);
            $finish;
        end
        arg_0 = 8'b01101100;
        #0;
        if (9'sb001101100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 108", 9'sb001101100, out);
            $finish;
        end
        arg_0 = 8'b01101101;
        #0;
        if (9'sb001101101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 109", 9'sb001101101, out);
            $finish;
        end
        arg_0 = 8'b01101110;
        #0;
        if (9'sb001101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 110", 9'sb001101110, out);
            $finish;
        end
        arg_0 = 8'b01101111;
        #0;
        if (9'sb001101111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 111", 9'sb001101111, out);
            $finish;
        end
        arg_0 = 8'b01110000;
        #0;
        if (9'sb001110000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 112", 9'sb001110000, out);
            $finish;
        end
        arg_0 = 8'b01110001;
        #0;
        if (9'sb001110001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 113", 9'sb001110001, out);
            $finish;
        end
        arg_0 = 8'b01110010;
        #0;
        if (9'sb001110010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 114", 9'sb001110010, out);
            $finish;
        end
        arg_0 = 8'b01110011;
        #0;
        if (9'sb001110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 115", 9'sb001110011, out);
            $finish;
        end
        arg_0 = 8'b01110100;
        #0;
        if (9'sb001110100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 116", 9'sb001110100, out);
            $finish;
        end
        arg_0 = 8'b01110101;
        #0;
        if (9'sb001110101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 117", 9'sb001110101, out);
            $finish;
        end
        arg_0 = 8'b01110110;
        #0;
        if (9'sb001110110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 118", 9'sb001110110, out);
            $finish;
        end
        arg_0 = 8'b01110111;
        #0;
        if (9'sb001110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 119", 9'sb001110111, out);
            $finish;
        end
        arg_0 = 8'b01111000;
        #0;
        if (9'sb001111000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 120", 9'sb001111000, out);
            $finish;
        end
        arg_0 = 8'b01111001;
        #0;
        if (9'sb001111001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 121", 9'sb001111001, out);
            $finish;
        end
        arg_0 = 8'b01111010;
        #0;
        if (9'sb001111010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 122", 9'sb001111010, out);
            $finish;
        end
        arg_0 = 8'b01111011;
        #0;
        if (9'sb001111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 123", 9'sb001111011, out);
            $finish;
        end
        arg_0 = 8'b01111100;
        #0;
        if (9'sb001111100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 124", 9'sb001111100, out);
            $finish;
        end
        arg_0 = 8'b01111101;
        #0;
        if (9'sb001111101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 125", 9'sb001111101, out);
            $finish;
        end
        arg_0 = 8'b01111110;
        #0;
        if (9'sb001111110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 126", 9'sb001111110, out);
            $finish;
        end
        arg_0 = 8'b01111111;
        #0;
        if (9'sb001111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 127", 9'sb001111111, out);
            $finish;
        end
        arg_0 = 8'b10000000;
        #0;
        if (9'sb010000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 128", 9'sb010000000, out);
            $finish;
        end
        arg_0 = 8'b10000001;
        #0;
        if (9'sb010000001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 129", 9'sb010000001, out);
            $finish;
        end
        arg_0 = 8'b10000010;
        #0;
        if (9'sb010000010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 130", 9'sb010000010, out);
            $finish;
        end
        arg_0 = 8'b10000011;
        #0;
        if (9'sb010000011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 131", 9'sb010000011, out);
            $finish;
        end
        arg_0 = 8'b10000100;
        #0;
        if (9'sb010000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 132", 9'sb010000100, out);
            $finish;
        end
        arg_0 = 8'b10000101;
        #0;
        if (9'sb010000101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 133", 9'sb010000101, out);
            $finish;
        end
        arg_0 = 8'b10000110;
        #0;
        if (9'sb010000110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 134", 9'sb010000110, out);
            $finish;
        end
        arg_0 = 8'b10000111;
        #0;
        if (9'sb010000111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 135", 9'sb010000111, out);
            $finish;
        end
        arg_0 = 8'b10001000;
        #0;
        if (9'sb010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 136", 9'sb010001000, out);
            $finish;
        end
        arg_0 = 8'b10001001;
        #0;
        if (9'sb010001001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 137", 9'sb010001001, out);
            $finish;
        end
        arg_0 = 8'b10001010;
        #0;
        if (9'sb010001010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 138", 9'sb010001010, out);
            $finish;
        end
        arg_0 = 8'b10001011;
        #0;
        if (9'sb010001011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 139", 9'sb010001011, out);
            $finish;
        end
        arg_0 = 8'b10001100;
        #0;
        if (9'sb010001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 140", 9'sb010001100, out);
            $finish;
        end
        arg_0 = 8'b10001101;
        #0;
        if (9'sb010001101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 141", 9'sb010001101, out);
            $finish;
        end
        arg_0 = 8'b10001110;
        #0;
        if (9'sb010001110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 142", 9'sb010001110, out);
            $finish;
        end
        arg_0 = 8'b10001111;
        #0;
        if (9'sb010001111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 143", 9'sb010001111, out);
            $finish;
        end
        arg_0 = 8'b10010000;
        #0;
        if (9'sb010010000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 144", 9'sb010010000, out);
            $finish;
        end
        arg_0 = 8'b10010001;
        #0;
        if (9'sb010010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 145", 9'sb010010001, out);
            $finish;
        end
        arg_0 = 8'b10010010;
        #0;
        if (9'sb010010010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 146", 9'sb010010010, out);
            $finish;
        end
        arg_0 = 8'b10010011;
        #0;
        if (9'sb010010011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 147", 9'sb010010011, out);
            $finish;
        end
        arg_0 = 8'b10010100;
        #0;
        if (9'sb010010100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 148", 9'sb010010100, out);
            $finish;
        end
        arg_0 = 8'b10010101;
        #0;
        if (9'sb010010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 149", 9'sb010010101, out);
            $finish;
        end
        arg_0 = 8'b10010110;
        #0;
        if (9'sb010010110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 150", 9'sb010010110, out);
            $finish;
        end
        arg_0 = 8'b10010111;
        #0;
        if (9'sb010010111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 151", 9'sb010010111, out);
            $finish;
        end
        arg_0 = 8'b10011000;
        #0;
        if (9'sb010011000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 152", 9'sb010011000, out);
            $finish;
        end
        arg_0 = 8'b10011001;
        #0;
        if (9'sb010011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 153", 9'sb010011001, out);
            $finish;
        end
        arg_0 = 8'b10011010;
        #0;
        if (9'sb010011010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 154", 9'sb010011010, out);
            $finish;
        end
        arg_0 = 8'b10011011;
        #0;
        if (9'sb010011011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 155", 9'sb010011011, out);
            $finish;
        end
        arg_0 = 8'b10011100;
        #0;
        if (9'sb010011100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 156", 9'sb010011100, out);
            $finish;
        end
        arg_0 = 8'b10011101;
        #0;
        if (9'sb010011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 157", 9'sb010011101, out);
            $finish;
        end
        arg_0 = 8'b10011110;
        #0;
        if (9'sb010011110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 158", 9'sb010011110, out);
            $finish;
        end
        arg_0 = 8'b10011111;
        #0;
        if (9'sb010011111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 159", 9'sb010011111, out);
            $finish;
        end
        arg_0 = 8'b10100000;
        #0;
        if (9'sb010100000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 160", 9'sb010100000, out);
            $finish;
        end
        arg_0 = 8'b10100001;
        #0;
        if (9'sb010100001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 161", 9'sb010100001, out);
            $finish;
        end
        arg_0 = 8'b10100010;
        #0;
        if (9'sb010100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 162", 9'sb010100010, out);
            $finish;
        end
        arg_0 = 8'b10100011;
        #0;
        if (9'sb010100011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 163", 9'sb010100011, out);
            $finish;
        end
        arg_0 = 8'b10100100;
        #0;
        if (9'sb010100100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 164", 9'sb010100100, out);
            $finish;
        end
        arg_0 = 8'b10100101;
        #0;
        if (9'sb010100101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 165", 9'sb010100101, out);
            $finish;
        end
        arg_0 = 8'b10100110;
        #0;
        if (9'sb010100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 166", 9'sb010100110, out);
            $finish;
        end
        arg_0 = 8'b10100111;
        #0;
        if (9'sb010100111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 167", 9'sb010100111, out);
            $finish;
        end
        arg_0 = 8'b10101000;
        #0;
        if (9'sb010101000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 168", 9'sb010101000, out);
            $finish;
        end
        arg_0 = 8'b10101001;
        #0;
        if (9'sb010101001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 169", 9'sb010101001, out);
            $finish;
        end
        arg_0 = 8'b10101010;
        #0;
        if (9'sb010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 170", 9'sb010101010, out);
            $finish;
        end
        arg_0 = 8'b10101011;
        #0;
        if (9'sb010101011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 171", 9'sb010101011, out);
            $finish;
        end
        arg_0 = 8'b10101100;
        #0;
        if (9'sb010101100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 172", 9'sb010101100, out);
            $finish;
        end
        arg_0 = 8'b10101101;
        #0;
        if (9'sb010101101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 173", 9'sb010101101, out);
            $finish;
        end
        arg_0 = 8'b10101110;
        #0;
        if (9'sb010101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 174", 9'sb010101110, out);
            $finish;
        end
        arg_0 = 8'b10101111;
        #0;
        if (9'sb010101111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 175", 9'sb010101111, out);
            $finish;
        end
        arg_0 = 8'b10110000;
        #0;
        if (9'sb010110000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 176", 9'sb010110000, out);
            $finish;
        end
        arg_0 = 8'b10110001;
        #0;
        if (9'sb010110001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 177", 9'sb010110001, out);
            $finish;
        end
        arg_0 = 8'b10110010;
        #0;
        if (9'sb010110010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 178", 9'sb010110010, out);
            $finish;
        end
        arg_0 = 8'b10110011;
        #0;
        if (9'sb010110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 179", 9'sb010110011, out);
            $finish;
        end
        arg_0 = 8'b10110100;
        #0;
        if (9'sb010110100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 180", 9'sb010110100, out);
            $finish;
        end
        arg_0 = 8'b10110101;
        #0;
        if (9'sb010110101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 181", 9'sb010110101, out);
            $finish;
        end
        arg_0 = 8'b10110110;
        #0;
        if (9'sb010110110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 182", 9'sb010110110, out);
            $finish;
        end
        arg_0 = 8'b10110111;
        #0;
        if (9'sb010110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 183", 9'sb010110111, out);
            $finish;
        end
        arg_0 = 8'b10111000;
        #0;
        if (9'sb010111000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 184", 9'sb010111000, out);
            $finish;
        end
        arg_0 = 8'b10111001;
        #0;
        if (9'sb010111001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 185", 9'sb010111001, out);
            $finish;
        end
        arg_0 = 8'b10111010;
        #0;
        if (9'sb010111010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 186", 9'sb010111010, out);
            $finish;
        end
        arg_0 = 8'b10111011;
        #0;
        if (9'sb010111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 187", 9'sb010111011, out);
            $finish;
        end
        arg_0 = 8'b10111100;
        #0;
        if (9'sb010111100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 188", 9'sb010111100, out);
            $finish;
        end
        arg_0 = 8'b10111101;
        #0;
        if (9'sb010111101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 189", 9'sb010111101, out);
            $finish;
        end
        arg_0 = 8'b10111110;
        #0;
        if (9'sb010111110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 190", 9'sb010111110, out);
            $finish;
        end
        arg_0 = 8'b10111111;
        #0;
        if (9'sb010111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 191", 9'sb010111111, out);
            $finish;
        end
        arg_0 = 8'b11000000;
        #0;
        if (9'sb011000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 192", 9'sb011000000, out);
            $finish;
        end
        arg_0 = 8'b11000001;
        #0;
        if (9'sb011000001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 193", 9'sb011000001, out);
            $finish;
        end
        arg_0 = 8'b11000010;
        #0;
        if (9'sb011000010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 194", 9'sb011000010, out);
            $finish;
        end
        arg_0 = 8'b11000011;
        #0;
        if (9'sb011000011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 195", 9'sb011000011, out);
            $finish;
        end
        arg_0 = 8'b11000100;
        #0;
        if (9'sb011000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 196", 9'sb011000100, out);
            $finish;
        end
        arg_0 = 8'b11000101;
        #0;
        if (9'sb011000101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 197", 9'sb011000101, out);
            $finish;
        end
        arg_0 = 8'b11000110;
        #0;
        if (9'sb011000110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 198", 9'sb011000110, out);
            $finish;
        end
        arg_0 = 8'b11000111;
        #0;
        if (9'sb011000111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 199", 9'sb011000111, out);
            $finish;
        end
        arg_0 = 8'b11001000;
        #0;
        if (9'sb011001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 200", 9'sb011001000, out);
            $finish;
        end
        arg_0 = 8'b11001001;
        #0;
        if (9'sb011001001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 201", 9'sb011001001, out);
            $finish;
        end
        arg_0 = 8'b11001010;
        #0;
        if (9'sb011001010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 202", 9'sb011001010, out);
            $finish;
        end
        arg_0 = 8'b11001011;
        #0;
        if (9'sb011001011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 203", 9'sb011001011, out);
            $finish;
        end
        arg_0 = 8'b11001100;
        #0;
        if (9'sb011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 204", 9'sb011001100, out);
            $finish;
        end
        arg_0 = 8'b11001101;
        #0;
        if (9'sb011001101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 205", 9'sb011001101, out);
            $finish;
        end
        arg_0 = 8'b11001110;
        #0;
        if (9'sb011001110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 206", 9'sb011001110, out);
            $finish;
        end
        arg_0 = 8'b11001111;
        #0;
        if (9'sb011001111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 207", 9'sb011001111, out);
            $finish;
        end
        arg_0 = 8'b11010000;
        #0;
        if (9'sb011010000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 208", 9'sb011010000, out);
            $finish;
        end
        arg_0 = 8'b11010001;
        #0;
        if (9'sb011010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 209", 9'sb011010001, out);
            $finish;
        end
        arg_0 = 8'b11010010;
        #0;
        if (9'sb011010010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 210", 9'sb011010010, out);
            $finish;
        end
        arg_0 = 8'b11010011;
        #0;
        if (9'sb011010011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 211", 9'sb011010011, out);
            $finish;
        end
        arg_0 = 8'b11010100;
        #0;
        if (9'sb011010100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 212", 9'sb011010100, out);
            $finish;
        end
        arg_0 = 8'b11010101;
        #0;
        if (9'sb011010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 213", 9'sb011010101, out);
            $finish;
        end
        arg_0 = 8'b11010110;
        #0;
        if (9'sb011010110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 214", 9'sb011010110, out);
            $finish;
        end
        arg_0 = 8'b11010111;
        #0;
        if (9'sb011010111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 215", 9'sb011010111, out);
            $finish;
        end
        arg_0 = 8'b11011000;
        #0;
        if (9'sb011011000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 216", 9'sb011011000, out);
            $finish;
        end
        arg_0 = 8'b11011001;
        #0;
        if (9'sb011011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 217", 9'sb011011001, out);
            $finish;
        end
        arg_0 = 8'b11011010;
        #0;
        if (9'sb011011010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 218", 9'sb011011010, out);
            $finish;
        end
        arg_0 = 8'b11011011;
        #0;
        if (9'sb011011011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 219", 9'sb011011011, out);
            $finish;
        end
        arg_0 = 8'b11011100;
        #0;
        if (9'sb011011100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 220", 9'sb011011100, out);
            $finish;
        end
        arg_0 = 8'b11011101;
        #0;
        if (9'sb011011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 221", 9'sb011011101, out);
            $finish;
        end
        arg_0 = 8'b11011110;
        #0;
        if (9'sb011011110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 222", 9'sb011011110, out);
            $finish;
        end
        arg_0 = 8'b11011111;
        #0;
        if (9'sb011011111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 223", 9'sb011011111, out);
            $finish;
        end
        arg_0 = 8'b11100000;
        #0;
        if (9'sb011100000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 224", 9'sb011100000, out);
            $finish;
        end
        arg_0 = 8'b11100001;
        #0;
        if (9'sb011100001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 225", 9'sb011100001, out);
            $finish;
        end
        arg_0 = 8'b11100010;
        #0;
        if (9'sb011100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 226", 9'sb011100010, out);
            $finish;
        end
        arg_0 = 8'b11100011;
        #0;
        if (9'sb011100011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 227", 9'sb011100011, out);
            $finish;
        end
        arg_0 = 8'b11100100;
        #0;
        if (9'sb011100100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 228", 9'sb011100100, out);
            $finish;
        end
        arg_0 = 8'b11100101;
        #0;
        if (9'sb011100101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 229", 9'sb011100101, out);
            $finish;
        end
        arg_0 = 8'b11100110;
        #0;
        if (9'sb011100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 230", 9'sb011100110, out);
            $finish;
        end
        arg_0 = 8'b11100111;
        #0;
        if (9'sb011100111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 231", 9'sb011100111, out);
            $finish;
        end
        arg_0 = 8'b11101000;
        #0;
        if (9'sb011101000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 232", 9'sb011101000, out);
            $finish;
        end
        arg_0 = 8'b11101001;
        #0;
        if (9'sb011101001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 233", 9'sb011101001, out);
            $finish;
        end
        arg_0 = 8'b11101010;
        #0;
        if (9'sb011101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 234", 9'sb011101010, out);
            $finish;
        end
        arg_0 = 8'b11101011;
        #0;
        if (9'sb011101011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 235", 9'sb011101011, out);
            $finish;
        end
        arg_0 = 8'b11101100;
        #0;
        if (9'sb011101100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 236", 9'sb011101100, out);
            $finish;
        end
        arg_0 = 8'b11101101;
        #0;
        if (9'sb011101101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 237", 9'sb011101101, out);
            $finish;
        end
        arg_0 = 8'b11101110;
        #0;
        if (9'sb011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 238", 9'sb011101110, out);
            $finish;
        end
        arg_0 = 8'b11101111;
        #0;
        if (9'sb011101111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 239", 9'sb011101111, out);
            $finish;
        end
        arg_0 = 8'b11110000;
        #0;
        if (9'sb011110000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 240", 9'sb011110000, out);
            $finish;
        end
        arg_0 = 8'b11110001;
        #0;
        if (9'sb011110001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 241", 9'sb011110001, out);
            $finish;
        end
        arg_0 = 8'b11110010;
        #0;
        if (9'sb011110010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 242", 9'sb011110010, out);
            $finish;
        end
        arg_0 = 8'b11110011;
        #0;
        if (9'sb011110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 243", 9'sb011110011, out);
            $finish;
        end
        arg_0 = 8'b11110100;
        #0;
        if (9'sb011110100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 244", 9'sb011110100, out);
            $finish;
        end
        arg_0 = 8'b11110101;
        #0;
        if (9'sb011110101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 245", 9'sb011110101, out);
            $finish;
        end
        arg_0 = 8'b11110110;
        #0;
        if (9'sb011110110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 246", 9'sb011110110, out);
            $finish;
        end
        arg_0 = 8'b11110111;
        #0;
        if (9'sb011110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 247", 9'sb011110111, out);
            $finish;
        end
        arg_0 = 8'b11111000;
        #0;
        if (9'sb011111000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 248", 9'sb011111000, out);
            $finish;
        end
        arg_0 = 8'b11111001;
        #0;
        if (9'sb011111001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 249", 9'sb011111001, out);
            $finish;
        end
        arg_0 = 8'b11111010;
        #0;
        if (9'sb011111010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 250", 9'sb011111010, out);
            $finish;
        end
        arg_0 = 8'b11111011;
        #0;
        if (9'sb011111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 251", 9'sb011111011, out);
            $finish;
        end
        arg_0 = 8'b11111100;
        #0;
        if (9'sb011111100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 252", 9'sb011111100, out);
            $finish;
        end
        arg_0 = 8'b11111101;
        #0;
        if (9'sb011111101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 253", 9'sb011111101, out);
            $finish;
        end
        arg_0 = 8'b11111110;
        #0;
        if (9'sb011111110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 254", 9'sb011111110, out);
            $finish;
        end
        arg_0 = 8'b11111111;
        #0;
        if (9'sb011111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 255", 9'sb011111111, out);
            $finish;
        end
        $display("TESTBENCH OK", );
        $finish;
    end
endmodule
//
module dut(input wire [7:0] arg_0, output reg [8:0] out);
    reg [0:0] r9;
    reg [0:0] r10;
    reg [0:0] r11;
    reg [0:0] r12;
    reg [0:0] r13;
    reg [0:0] r14;
    reg [0:0] r15;
    reg [0:0] r16;
    always @(*) begin
        r9 = arg_0[0];
        r10 = arg_0[1];
        r11 = arg_0[2];
        r12 = arg_0[3];
        r13 = arg_0[4];
        r14 = arg_0[5];
        r15 = arg_0[6];
        r16 = arg_0[7];
        // let a = a.val();
        //
        // let c = a.xsgn();
        //
        // signal(c)
        //
        out = { 1'b0, r16, r15, r14, r13, r12, r11, r10, r9 };
    end
endmodule
