// Autogenerated testbench for kernel_do_stuff
module testbench();
    wire [7:0] out;
    reg [0:0] arg_0;
    assign out = kernel_do_stuff(arg_0);
    initial begin
        arg_0 = 1'b0;
        #0;
        if (8'b00000111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 0", 8'b00000111, out);
            $finish;
        end
        arg_0 = 1'b1;
        #0;
        if (8'b00000011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 1", 8'b00000011, out);
            $finish;
        end
        $display("TESTBENCH OK", );
        $finish;
    end
    function [7:0] kernel_do_stuff(input reg [0:0] arg_0);
        reg [0:0] or0;
        reg [0:0] or1;
        reg [127:0] or2;
        reg [7:0] or3;
        localparam ol0 = 128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011;
        localparam ol1 = 128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000111;
        begin
            or0 = arg_0;
            // let a = a.val();
            //
            // let j = if a.any() {
            //    3
            // }
            //  else {
            //    7
            // }
            // ;
            //
            or1 = |(or0);
            // 3
            //
            // 7
            //
            or2 = (or1) ? (ol0) : (ol1);
            // signal(bits(j))
            //
            or3 = or2[7:0];
            kernel_do_stuff = or3;
        end
    endfunction
endmodule
