// Autogenerated testbench for dut
module testbench();
    wire [8:0] out;
    reg [7:0] arg_0;
    dut t (.out(out),.arg_0(arg_0));
    initial begin
        arg_0 = 8'b00000000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 0", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00000001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 1", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00000010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 2", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00000011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 3", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00000100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 4", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00000101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 5", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00000110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 6", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00000111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 7", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00001000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 8", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00001001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 9", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00001010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 10", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00001011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 11", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00001100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 12", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00001101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 13", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00001110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 14", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00001111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 15", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00010000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 16", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00010001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 17", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00010010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 18", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00010011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 19", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00010100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 20", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00010101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 21", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00010110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 22", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00010111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 23", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00011000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 24", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00011001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 25", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00011010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 26", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00011011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 27", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00011100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 28", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00011101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 29", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00011110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 30", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00011111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 31", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00100000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 32", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00100001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 33", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00100010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 34", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00100011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 35", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00100100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 36", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00100101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 37", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00100110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 38", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00100111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 39", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00101000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 40", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00101001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 41", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00101010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 42", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00101011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 43", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00101100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 44", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00101101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 45", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00101110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 46", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00101111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 47", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00110000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 48", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00110001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 49", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00110010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 50", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00110011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 51", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00110100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 52", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00110101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 53", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00110110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 54", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00110111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 55", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00111000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 56", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00111001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 57", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00111010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 58", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00111011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 59", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00111100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 60", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00111101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 61", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00111110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 62", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b00111111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 63", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01000000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 64", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01000001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 65", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01000010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 66", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01000011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 67", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01000100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 68", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01000101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 69", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01000110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 70", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01000111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 71", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01001000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 72", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01001001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 73", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01001010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 74", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01001011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 75", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01001100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 76", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01001101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 77", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01001110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 78", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01001111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 79", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01010000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 80", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01010001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 81", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01010010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 82", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01010011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 83", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01010100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 84", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01010101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 85", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01010110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 86", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01010111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 87", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01011000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 88", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01011001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 89", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01011010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 90", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01011011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 91", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01011100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 92", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01011101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 93", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01011110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 94", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01011111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 95", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01100000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 96", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01100001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 97", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01100010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 98", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01100011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 99", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01100100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 100", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01100101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 101", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01100110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 102", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01100111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 103", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01101000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 104", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01101001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 105", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01101010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 106", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01101011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 107", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01101100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 108", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01101101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 109", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01101110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 110", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01101111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 111", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01110000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 112", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01110001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 113", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01110010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 114", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01110011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 115", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01110100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 116", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01110101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 117", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01110110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 118", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01110111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 119", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01111000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 120", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01111001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 121", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01111010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 122", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01111011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 123", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01111100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 124", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01111101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 125", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01111110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 126", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b01111111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 127", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10000000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 128", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10000001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 129", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10000010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 130", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10000011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 131", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10000100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 132", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10000101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 133", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10000110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 134", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10000111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 135", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10001000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 136", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10001001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 137", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10001010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 138", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10001011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 139", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10001100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 140", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10001101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 141", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10001110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 142", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10001111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 143", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10010000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 144", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10010001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 145", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10010010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 146", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10010011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 147", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10010100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 148", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10010101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 149", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10010110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 150", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10010111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 151", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10011000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 152", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10011001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 153", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10011010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 154", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10011011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 155", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10011100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 156", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10011101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 157", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10011110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 158", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10011111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 159", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10100000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 160", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10100001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 161", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10100010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 162", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10100011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 163", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10100100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 164", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10100101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 165", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10100110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 166", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10100111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 167", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10101000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 168", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10101001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 169", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10101010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 170", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10101011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 171", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10101100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 172", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10101101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 173", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10101110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 174", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10101111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 175", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10110000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 176", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10110001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 177", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10110010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 178", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10110011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 179", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10110100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 180", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10110101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 181", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10110110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 182", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10110111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 183", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10111000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 184", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10111001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 185", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10111010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 186", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10111011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 187", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10111100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 188", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10111101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 189", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10111110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 190", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b10111111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 191", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11000000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 192", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11000001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 193", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11000010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 194", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11000011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 195", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11000100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 196", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11000101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 197", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11000110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 198", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11000111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 199", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11001000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 200", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11001001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 201", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11001010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 202", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11001011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 203", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11001100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 204", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11001101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 205", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11001110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 206", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11001111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 207", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11010000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 208", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11010001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 209", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11010010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 210", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11010011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 211", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11010100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 212", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11010101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 213", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11010110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 214", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11010111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 215", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11011000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 216", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11011001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 217", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11011010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 218", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11011011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 219", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11011100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 220", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11011101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 221", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11011110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 222", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11011111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 223", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11100000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 224", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11100001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 225", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11100010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 226", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11100011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 227", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11100100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 228", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11100101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 229", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11100110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 230", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11100111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 231", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11101000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 232", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11101001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 233", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11101010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 234", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11101011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 235", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11101100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 236", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11101101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 237", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11101110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 238", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11101111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 239", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11110000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 240", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11110001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 241", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11110010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 242", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11110011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 243", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11110100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 244", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11110101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 245", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11110110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 246", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11110111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 247", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11111000;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 248", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11111001;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 249", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11111010;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 250", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11111011;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 251", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11111100;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 252", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11111101;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 253", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11111110;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 254", 9'b000000000, out);
            $finish;
        end
        arg_0 = 8'b11111111;
        #0;
        if (9'b000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 255", 9'b000000000, out);
            $finish;
        end
        $display("TESTBENCH OK", );
        $finish;
    end
endmodule
//
module dut(input wire [7:0] arg_0, output reg [8:0] out);
    reg [0:0] r0;
    reg [0:0] r1;
    reg [0:0] r2;
    reg [0:0] r3;
    reg [0:0] r4;
    reg [0:0] r5;
    reg [0:0] r6;
    reg [0:0] r7;
    reg [0:0] r8;
    reg [0:0] r26;
    reg [0:0] r27;
    reg [0:0] r28;
    reg [0:0] r29;
    reg [0:0] r30;
    reg [0:0] r31;
    reg [0:0] r32;
    reg [0:0] r33;
    reg [0:0] r45;
    reg [0:0] r46;
    reg [0:0] r47;
    reg [0:0] r48;
    reg [0:0] r49;
    reg [0:0] r50;
    reg [0:0] r51;
    reg [0:0] r52;
    reg [0:0] r53;
    reg [0:0] r54;
    reg [0:0] r55;
    reg [0:0] r100;
    reg [0:0] r101;
    reg [0:0] r102;
    reg [0:0] r103;
    reg [0:0] r104;
    reg [0:0] r105;
    reg [0:0] r106;
    reg [0:0] r107;
    reg [0:0] r108;
    reg [0:0] r109;
    reg [0:0] r110;
    reg [0:0] r111;
    reg [0:0] r112;
    reg [0:0] r113;
    reg [0:0] r114;
    reg [0:0] r115;
    reg [0:0] r116;
    reg [0:0] r117;
    always @(*) begin
        r1 = arg_0[0];
        r2 = arg_0[1];
        r3 = arg_0[2];
        r4 = arg_0[3];
        r5 = arg_0[4];
        r6 = arg_0[5];
        r7 = arg_0[6];
        r8 = arg_0[7];
        // let j = validify(i)?;
        //
        // if i.any() {
        //    Some(i)
        // }
        //  else {
        //    None()
        // }
        //
        //
        // Some(i)
        //
        // None()
        //
        // match validify(j) {
        //    Some(_k, )#true => None(),
        //    _#false => Some(j),
        // }
        //
        // if i.any() {
        //    Some(i)
        // }
        //  else {
        //    None()
        // }
        //
        //
        // Some(i)
        //
        // None()
        //
        { r0 } = |({ r8, r7, r6, r5, r4, r3, r2, r1 });
        r26 = r0 & r1;
        r27 = r0 & r2;
        r28 = r0 & r3;
        r29 = r0 & r4;
        r30 = r0 & r5;
        r31 = r0 & r6;
        r32 = r0 & r7;
        r33 = r0 & r8;
        r53 = (r0) ? (1'b0) : (r0);
        r54 = ~(r0);
        r45 = (r0) ? (1'b0) : (r26);
        r46 = (r0) ? (1'b0) : (r27);
        r47 = (r0) ? (1'b0) : (r28);
        r48 = (r0) ? (1'b0) : (r29);
        r49 = (r0) ? (1'b0) : (r30);
        r50 = (r0) ? (1'b0) : (r31);
        r51 = (r0) ? (1'b0) : (r32);
        r52 = (r0) ? (1'b0) : (r33);
        { r55 } = |({ r33, r32, r31, r30, r29, r28, r27, r26 });
        r100 = (r55) ? (1'b0) : (r26);
        r101 = (r55) ? (1'b0) : (r27);
        r102 = (r55) ? (1'b0) : (r28);
        r103 = (r55) ? (1'b0) : (r29);
        r104 = (r55) ? (1'b0) : (r30);
        r105 = (r55) ? (1'b0) : (r31);
        r106 = (r55) ? (1'b0) : (r32);
        r107 = (r55) ? (1'b0) : (r33);
        r108 = ~(r55);
        r109 = (r54) ? (r45) : (r100);
        r110 = (r54) ? (r46) : (r101);
        r111 = (r54) ? (r47) : (r102);
        r112 = (r54) ? (r48) : (r103);
        r113 = (r54) ? (r49) : (r104);
        r114 = (r54) ? (r50) : (r105);
        r115 = (r54) ? (r51) : (r106);
        r116 = (r54) ? (r52) : (r107);
        r117 = (r54) ? (r53) : (r108);
        out = { r117, r116, r115, r114, r113, r112, r111, r110, r109 };
    end
endmodule
