// Autogenerated testbench for dut
module testbench();
    wire [3:0] out;
    reg [7:0] arg_0;
    dut t (.out(out),.arg_0(arg_0));
    initial begin
        arg_0 = 8'b00000000;
        #0;
        if (4'b0001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 0", 4'b0001, out);
            $finish;
        end
        arg_0 = 8'b00000001;
        #0;
        if (4'b0010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 1", 4'b0010, out);
            $finish;
        end
        arg_0 = 8'b00000010;
        #0;
        if (4'b0011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 2", 4'b0011, out);
            $finish;
        end
        arg_0 = 8'b00000011;
        #0;
        if (4'b0100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 3", 4'b0100, out);
            $finish;
        end
        arg_0 = 8'b00000100;
        #0;
        if (4'b0101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 4", 4'b0101, out);
            $finish;
        end
        arg_0 = 8'b00000101;
        #0;
        if (4'b0110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 5", 4'b0110, out);
            $finish;
        end
        arg_0 = 8'b00000110;
        #0;
        if (4'b0111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 6", 4'b0111, out);
            $finish;
        end
        arg_0 = 8'b00000111;
        #0;
        if (4'b1000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 7", 4'b1000, out);
            $finish;
        end
        arg_0 = 8'b00001000;
        #0;
        if (4'b1001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 8", 4'b1001, out);
            $finish;
        end
        arg_0 = 8'b00001001;
        #0;
        if (4'b1010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 9", 4'b1010, out);
            $finish;
        end
        arg_0 = 8'b00001010;
        #0;
        if (4'b1011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 10", 4'b1011, out);
            $finish;
        end
        arg_0 = 8'b00001011;
        #0;
        if (4'b1100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 11", 4'b1100, out);
            $finish;
        end
        arg_0 = 8'b00001100;
        #0;
        if (4'b1101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 12", 4'b1101, out);
            $finish;
        end
        arg_0 = 8'b00001101;
        #0;
        if (4'b1110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 13", 4'b1110, out);
            $finish;
        end
        arg_0 = 8'b00001110;
        #0;
        if (4'b1111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 14", 4'b1111, out);
            $finish;
        end
        arg_0 = 8'b00001111;
        #0;
        if (4'b0000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 15", 4'b0000, out);
            $finish;
        end
        arg_0 = 8'b00010000;
        #0;
        if (4'b0001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 16", 4'b0001, out);
            $finish;
        end
        arg_0 = 8'b00010001;
        #0;
        if (4'b0010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 17", 4'b0010, out);
            $finish;
        end
        arg_0 = 8'b00010010;
        #0;
        if (4'b0011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 18", 4'b0011, out);
            $finish;
        end
        arg_0 = 8'b00010011;
        #0;
        if (4'b0100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 19", 4'b0100, out);
            $finish;
        end
        arg_0 = 8'b00010100;
        #0;
        if (4'b0101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 20", 4'b0101, out);
            $finish;
        end
        arg_0 = 8'b00010101;
        #0;
        if (4'b0110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 21", 4'b0110, out);
            $finish;
        end
        arg_0 = 8'b00010110;
        #0;
        if (4'b0111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 22", 4'b0111, out);
            $finish;
        end
        arg_0 = 8'b00010111;
        #0;
        if (4'b1000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 23", 4'b1000, out);
            $finish;
        end
        arg_0 = 8'b00011000;
        #0;
        if (4'b1001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 24", 4'b1001, out);
            $finish;
        end
        arg_0 = 8'b00011001;
        #0;
        if (4'b1010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 25", 4'b1010, out);
            $finish;
        end
        arg_0 = 8'b00011010;
        #0;
        if (4'b1011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 26", 4'b1011, out);
            $finish;
        end
        arg_0 = 8'b00011011;
        #0;
        if (4'b1100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 27", 4'b1100, out);
            $finish;
        end
        arg_0 = 8'b00011100;
        #0;
        if (4'b1101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 28", 4'b1101, out);
            $finish;
        end
        arg_0 = 8'b00011101;
        #0;
        if (4'b1110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 29", 4'b1110, out);
            $finish;
        end
        arg_0 = 8'b00011110;
        #0;
        if (4'b1111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 30", 4'b1111, out);
            $finish;
        end
        arg_0 = 8'b00011111;
        #0;
        if (4'b0000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 31", 4'b0000, out);
            $finish;
        end
        arg_0 = 8'b00100000;
        #0;
        if (4'b0001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 32", 4'b0001, out);
            $finish;
        end
        arg_0 = 8'b00100001;
        #0;
        if (4'b0010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 33", 4'b0010, out);
            $finish;
        end
        arg_0 = 8'b00100010;
        #0;
        if (4'b0011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 34", 4'b0011, out);
            $finish;
        end
        arg_0 = 8'b00100011;
        #0;
        if (4'b0100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 35", 4'b0100, out);
            $finish;
        end
        arg_0 = 8'b00100100;
        #0;
        if (4'b0101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 36", 4'b0101, out);
            $finish;
        end
        arg_0 = 8'b00100101;
        #0;
        if (4'b0110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 37", 4'b0110, out);
            $finish;
        end
        arg_0 = 8'b00100110;
        #0;
        if (4'b0111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 38", 4'b0111, out);
            $finish;
        end
        arg_0 = 8'b00100111;
        #0;
        if (4'b1000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 39", 4'b1000, out);
            $finish;
        end
        arg_0 = 8'b00101000;
        #0;
        if (4'b1001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 40", 4'b1001, out);
            $finish;
        end
        arg_0 = 8'b00101001;
        #0;
        if (4'b1010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 41", 4'b1010, out);
            $finish;
        end
        arg_0 = 8'b00101010;
        #0;
        if (4'b1011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 42", 4'b1011, out);
            $finish;
        end
        arg_0 = 8'b00101011;
        #0;
        if (4'b1100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 43", 4'b1100, out);
            $finish;
        end
        arg_0 = 8'b00101100;
        #0;
        if (4'b1101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 44", 4'b1101, out);
            $finish;
        end
        arg_0 = 8'b00101101;
        #0;
        if (4'b1110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 45", 4'b1110, out);
            $finish;
        end
        arg_0 = 8'b00101110;
        #0;
        if (4'b1111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 46", 4'b1111, out);
            $finish;
        end
        arg_0 = 8'b00101111;
        #0;
        if (4'b0000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 47", 4'b0000, out);
            $finish;
        end
        arg_0 = 8'b00110000;
        #0;
        if (4'b0001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 48", 4'b0001, out);
            $finish;
        end
        arg_0 = 8'b00110001;
        #0;
        if (4'b0010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 49", 4'b0010, out);
            $finish;
        end
        arg_0 = 8'b00110010;
        #0;
        if (4'b0011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 50", 4'b0011, out);
            $finish;
        end
        arg_0 = 8'b00110011;
        #0;
        if (4'b0100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 51", 4'b0100, out);
            $finish;
        end
        arg_0 = 8'b00110100;
        #0;
        if (4'b0101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 52", 4'b0101, out);
            $finish;
        end
        arg_0 = 8'b00110101;
        #0;
        if (4'b0110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 53", 4'b0110, out);
            $finish;
        end
        arg_0 = 8'b00110110;
        #0;
        if (4'b0111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 54", 4'b0111, out);
            $finish;
        end
        arg_0 = 8'b00110111;
        #0;
        if (4'b1000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 55", 4'b1000, out);
            $finish;
        end
        arg_0 = 8'b00111000;
        #0;
        if (4'b1001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 56", 4'b1001, out);
            $finish;
        end
        arg_0 = 8'b00111001;
        #0;
        if (4'b1010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 57", 4'b1010, out);
            $finish;
        end
        arg_0 = 8'b00111010;
        #0;
        if (4'b1011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 58", 4'b1011, out);
            $finish;
        end
        arg_0 = 8'b00111011;
        #0;
        if (4'b1100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 59", 4'b1100, out);
            $finish;
        end
        arg_0 = 8'b00111100;
        #0;
        if (4'b1101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 60", 4'b1101, out);
            $finish;
        end
        arg_0 = 8'b00111101;
        #0;
        if (4'b1110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 61", 4'b1110, out);
            $finish;
        end
        arg_0 = 8'b00111110;
        #0;
        if (4'b1111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 62", 4'b1111, out);
            $finish;
        end
        arg_0 = 8'b00111111;
        #0;
        if (4'b0000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 63", 4'b0000, out);
            $finish;
        end
        arg_0 = 8'b01000000;
        #0;
        if (4'b0001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 64", 4'b0001, out);
            $finish;
        end
        arg_0 = 8'b01000001;
        #0;
        if (4'b0010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 65", 4'b0010, out);
            $finish;
        end
        arg_0 = 8'b01000010;
        #0;
        if (4'b0011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 66", 4'b0011, out);
            $finish;
        end
        arg_0 = 8'b01000011;
        #0;
        if (4'b0100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 67", 4'b0100, out);
            $finish;
        end
        arg_0 = 8'b01000100;
        #0;
        if (4'b0101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 68", 4'b0101, out);
            $finish;
        end
        arg_0 = 8'b01000101;
        #0;
        if (4'b0110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 69", 4'b0110, out);
            $finish;
        end
        arg_0 = 8'b01000110;
        #0;
        if (4'b0111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 70", 4'b0111, out);
            $finish;
        end
        arg_0 = 8'b01000111;
        #0;
        if (4'b1000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 71", 4'b1000, out);
            $finish;
        end
        arg_0 = 8'b01001000;
        #0;
        if (4'b1001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 72", 4'b1001, out);
            $finish;
        end
        arg_0 = 8'b01001001;
        #0;
        if (4'b1010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 73", 4'b1010, out);
            $finish;
        end
        arg_0 = 8'b01001010;
        #0;
        if (4'b1011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 74", 4'b1011, out);
            $finish;
        end
        arg_0 = 8'b01001011;
        #0;
        if (4'b1100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 75", 4'b1100, out);
            $finish;
        end
        arg_0 = 8'b01001100;
        #0;
        if (4'b1101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 76", 4'b1101, out);
            $finish;
        end
        arg_0 = 8'b01001101;
        #0;
        if (4'b1110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 77", 4'b1110, out);
            $finish;
        end
        arg_0 = 8'b01001110;
        #0;
        if (4'b1111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 78", 4'b1111, out);
            $finish;
        end
        arg_0 = 8'b01001111;
        #0;
        if (4'b0000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 79", 4'b0000, out);
            $finish;
        end
        arg_0 = 8'b01010000;
        #0;
        if (4'b0001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 80", 4'b0001, out);
            $finish;
        end
        arg_0 = 8'b01010001;
        #0;
        if (4'b0010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 81", 4'b0010, out);
            $finish;
        end
        arg_0 = 8'b01010010;
        #0;
        if (4'b0011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 82", 4'b0011, out);
            $finish;
        end
        arg_0 = 8'b01010011;
        #0;
        if (4'b0100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 83", 4'b0100, out);
            $finish;
        end
        arg_0 = 8'b01010100;
        #0;
        if (4'b0101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 84", 4'b0101, out);
            $finish;
        end
        arg_0 = 8'b01010101;
        #0;
        if (4'b0110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 85", 4'b0110, out);
            $finish;
        end
        arg_0 = 8'b01010110;
        #0;
        if (4'b0111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 86", 4'b0111, out);
            $finish;
        end
        arg_0 = 8'b01010111;
        #0;
        if (4'b1000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 87", 4'b1000, out);
            $finish;
        end
        arg_0 = 8'b01011000;
        #0;
        if (4'b1001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 88", 4'b1001, out);
            $finish;
        end
        arg_0 = 8'b01011001;
        #0;
        if (4'b1010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 89", 4'b1010, out);
            $finish;
        end
        arg_0 = 8'b01011010;
        #0;
        if (4'b1011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 90", 4'b1011, out);
            $finish;
        end
        arg_0 = 8'b01011011;
        #0;
        if (4'b1100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 91", 4'b1100, out);
            $finish;
        end
        arg_0 = 8'b01011100;
        #0;
        if (4'b1101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 92", 4'b1101, out);
            $finish;
        end
        arg_0 = 8'b01011101;
        #0;
        if (4'b1110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 93", 4'b1110, out);
            $finish;
        end
        arg_0 = 8'b01011110;
        #0;
        if (4'b1111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 94", 4'b1111, out);
            $finish;
        end
        arg_0 = 8'b01011111;
        #0;
        if (4'b0000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 95", 4'b0000, out);
            $finish;
        end
        arg_0 = 8'b01100000;
        #0;
        if (4'b0001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 96", 4'b0001, out);
            $finish;
        end
        arg_0 = 8'b01100001;
        #0;
        if (4'b0010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 97", 4'b0010, out);
            $finish;
        end
        arg_0 = 8'b01100010;
        #0;
        if (4'b0011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 98", 4'b0011, out);
            $finish;
        end
        arg_0 = 8'b01100011;
        #0;
        if (4'b0100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 99", 4'b0100, out);
            $finish;
        end
        arg_0 = 8'b01100100;
        #0;
        if (4'b0101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 100", 4'b0101, out);
            $finish;
        end
        arg_0 = 8'b01100101;
        #0;
        if (4'b0110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 101", 4'b0110, out);
            $finish;
        end
        arg_0 = 8'b01100110;
        #0;
        if (4'b0111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 102", 4'b0111, out);
            $finish;
        end
        arg_0 = 8'b01100111;
        #0;
        if (4'b1000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 103", 4'b1000, out);
            $finish;
        end
        arg_0 = 8'b01101000;
        #0;
        if (4'b1001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 104", 4'b1001, out);
            $finish;
        end
        arg_0 = 8'b01101001;
        #0;
        if (4'b1010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 105", 4'b1010, out);
            $finish;
        end
        arg_0 = 8'b01101010;
        #0;
        if (4'b1011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 106", 4'b1011, out);
            $finish;
        end
        arg_0 = 8'b01101011;
        #0;
        if (4'b1100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 107", 4'b1100, out);
            $finish;
        end
        arg_0 = 8'b01101100;
        #0;
        if (4'b1101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 108", 4'b1101, out);
            $finish;
        end
        arg_0 = 8'b01101101;
        #0;
        if (4'b1110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 109", 4'b1110, out);
            $finish;
        end
        arg_0 = 8'b01101110;
        #0;
        if (4'b1111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 110", 4'b1111, out);
            $finish;
        end
        arg_0 = 8'b01101111;
        #0;
        if (4'b0000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 111", 4'b0000, out);
            $finish;
        end
        arg_0 = 8'b01110000;
        #0;
        if (4'b0001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 112", 4'b0001, out);
            $finish;
        end
        arg_0 = 8'b01110001;
        #0;
        if (4'b0010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 113", 4'b0010, out);
            $finish;
        end
        arg_0 = 8'b01110010;
        #0;
        if (4'b0011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 114", 4'b0011, out);
            $finish;
        end
        arg_0 = 8'b01110011;
        #0;
        if (4'b0100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 115", 4'b0100, out);
            $finish;
        end
        arg_0 = 8'b01110100;
        #0;
        if (4'b0101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 116", 4'b0101, out);
            $finish;
        end
        arg_0 = 8'b01110101;
        #0;
        if (4'b0110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 117", 4'b0110, out);
            $finish;
        end
        arg_0 = 8'b01110110;
        #0;
        if (4'b0111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 118", 4'b0111, out);
            $finish;
        end
        arg_0 = 8'b01110111;
        #0;
        if (4'b1000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 119", 4'b1000, out);
            $finish;
        end
        arg_0 = 8'b01111000;
        #0;
        if (4'b1001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 120", 4'b1001, out);
            $finish;
        end
        arg_0 = 8'b01111001;
        #0;
        if (4'b1010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 121", 4'b1010, out);
            $finish;
        end
        arg_0 = 8'b01111010;
        #0;
        if (4'b1011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 122", 4'b1011, out);
            $finish;
        end
        arg_0 = 8'b01111011;
        #0;
        if (4'b1100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 123", 4'b1100, out);
            $finish;
        end
        arg_0 = 8'b01111100;
        #0;
        if (4'b1101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 124", 4'b1101, out);
            $finish;
        end
        arg_0 = 8'b01111101;
        #0;
        if (4'b1110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 125", 4'b1110, out);
            $finish;
        end
        arg_0 = 8'b01111110;
        #0;
        if (4'b1111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 126", 4'b1111, out);
            $finish;
        end
        arg_0 = 8'b01111111;
        #0;
        if (4'b0000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 127", 4'b0000, out);
            $finish;
        end
        arg_0 = 8'b10000000;
        #0;
        if (4'b0001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 128", 4'b0001, out);
            $finish;
        end
        arg_0 = 8'b10000001;
        #0;
        if (4'b0010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 129", 4'b0010, out);
            $finish;
        end
        arg_0 = 8'b10000010;
        #0;
        if (4'b0011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 130", 4'b0011, out);
            $finish;
        end
        arg_0 = 8'b10000011;
        #0;
        if (4'b0100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 131", 4'b0100, out);
            $finish;
        end
        arg_0 = 8'b10000100;
        #0;
        if (4'b0101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 132", 4'b0101, out);
            $finish;
        end
        arg_0 = 8'b10000101;
        #0;
        if (4'b0110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 133", 4'b0110, out);
            $finish;
        end
        arg_0 = 8'b10000110;
        #0;
        if (4'b0111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 134", 4'b0111, out);
            $finish;
        end
        arg_0 = 8'b10000111;
        #0;
        if (4'b1000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 135", 4'b1000, out);
            $finish;
        end
        arg_0 = 8'b10001000;
        #0;
        if (4'b1001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 136", 4'b1001, out);
            $finish;
        end
        arg_0 = 8'b10001001;
        #0;
        if (4'b1010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 137", 4'b1010, out);
            $finish;
        end
        arg_0 = 8'b10001010;
        #0;
        if (4'b1011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 138", 4'b1011, out);
            $finish;
        end
        arg_0 = 8'b10001011;
        #0;
        if (4'b1100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 139", 4'b1100, out);
            $finish;
        end
        arg_0 = 8'b10001100;
        #0;
        if (4'b1101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 140", 4'b1101, out);
            $finish;
        end
        arg_0 = 8'b10001101;
        #0;
        if (4'b1110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 141", 4'b1110, out);
            $finish;
        end
        arg_0 = 8'b10001110;
        #0;
        if (4'b1111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 142", 4'b1111, out);
            $finish;
        end
        arg_0 = 8'b10001111;
        #0;
        if (4'b0000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 143", 4'b0000, out);
            $finish;
        end
        arg_0 = 8'b10010000;
        #0;
        if (4'b0001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 144", 4'b0001, out);
            $finish;
        end
        arg_0 = 8'b10010001;
        #0;
        if (4'b0010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 145", 4'b0010, out);
            $finish;
        end
        arg_0 = 8'b10010010;
        #0;
        if (4'b0011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 146", 4'b0011, out);
            $finish;
        end
        arg_0 = 8'b10010011;
        #0;
        if (4'b0100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 147", 4'b0100, out);
            $finish;
        end
        arg_0 = 8'b10010100;
        #0;
        if (4'b0101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 148", 4'b0101, out);
            $finish;
        end
        arg_0 = 8'b10010101;
        #0;
        if (4'b0110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 149", 4'b0110, out);
            $finish;
        end
        arg_0 = 8'b10010110;
        #0;
        if (4'b0111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 150", 4'b0111, out);
            $finish;
        end
        arg_0 = 8'b10010111;
        #0;
        if (4'b1000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 151", 4'b1000, out);
            $finish;
        end
        arg_0 = 8'b10011000;
        #0;
        if (4'b1001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 152", 4'b1001, out);
            $finish;
        end
        arg_0 = 8'b10011001;
        #0;
        if (4'b1010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 153", 4'b1010, out);
            $finish;
        end
        arg_0 = 8'b10011010;
        #0;
        if (4'b1011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 154", 4'b1011, out);
            $finish;
        end
        arg_0 = 8'b10011011;
        #0;
        if (4'b1100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 155", 4'b1100, out);
            $finish;
        end
        arg_0 = 8'b10011100;
        #0;
        if (4'b1101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 156", 4'b1101, out);
            $finish;
        end
        arg_0 = 8'b10011101;
        #0;
        if (4'b1110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 157", 4'b1110, out);
            $finish;
        end
        arg_0 = 8'b10011110;
        #0;
        if (4'b1111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 158", 4'b1111, out);
            $finish;
        end
        arg_0 = 8'b10011111;
        #0;
        if (4'b0000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 159", 4'b0000, out);
            $finish;
        end
        arg_0 = 8'b10100000;
        #0;
        if (4'b0001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 160", 4'b0001, out);
            $finish;
        end
        arg_0 = 8'b10100001;
        #0;
        if (4'b0010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 161", 4'b0010, out);
            $finish;
        end
        arg_0 = 8'b10100010;
        #0;
        if (4'b0011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 162", 4'b0011, out);
            $finish;
        end
        arg_0 = 8'b10100011;
        #0;
        if (4'b0100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 163", 4'b0100, out);
            $finish;
        end
        arg_0 = 8'b10100100;
        #0;
        if (4'b0101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 164", 4'b0101, out);
            $finish;
        end
        arg_0 = 8'b10100101;
        #0;
        if (4'b0110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 165", 4'b0110, out);
            $finish;
        end
        arg_0 = 8'b10100110;
        #0;
        if (4'b0111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 166", 4'b0111, out);
            $finish;
        end
        arg_0 = 8'b10100111;
        #0;
        if (4'b1000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 167", 4'b1000, out);
            $finish;
        end
        arg_0 = 8'b10101000;
        #0;
        if (4'b1001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 168", 4'b1001, out);
            $finish;
        end
        arg_0 = 8'b10101001;
        #0;
        if (4'b1010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 169", 4'b1010, out);
            $finish;
        end
        arg_0 = 8'b10101010;
        #0;
        if (4'b1011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 170", 4'b1011, out);
            $finish;
        end
        arg_0 = 8'b10101011;
        #0;
        if (4'b1100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 171", 4'b1100, out);
            $finish;
        end
        arg_0 = 8'b10101100;
        #0;
        if (4'b1101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 172", 4'b1101, out);
            $finish;
        end
        arg_0 = 8'b10101101;
        #0;
        if (4'b1110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 173", 4'b1110, out);
            $finish;
        end
        arg_0 = 8'b10101110;
        #0;
        if (4'b1111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 174", 4'b1111, out);
            $finish;
        end
        arg_0 = 8'b10101111;
        #0;
        if (4'b0000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 175", 4'b0000, out);
            $finish;
        end
        arg_0 = 8'b10110000;
        #0;
        if (4'b0001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 176", 4'b0001, out);
            $finish;
        end
        arg_0 = 8'b10110001;
        #0;
        if (4'b0010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 177", 4'b0010, out);
            $finish;
        end
        arg_0 = 8'b10110010;
        #0;
        if (4'b0011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 178", 4'b0011, out);
            $finish;
        end
        arg_0 = 8'b10110011;
        #0;
        if (4'b0100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 179", 4'b0100, out);
            $finish;
        end
        arg_0 = 8'b10110100;
        #0;
        if (4'b0101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 180", 4'b0101, out);
            $finish;
        end
        arg_0 = 8'b10110101;
        #0;
        if (4'b0110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 181", 4'b0110, out);
            $finish;
        end
        arg_0 = 8'b10110110;
        #0;
        if (4'b0111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 182", 4'b0111, out);
            $finish;
        end
        arg_0 = 8'b10110111;
        #0;
        if (4'b1000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 183", 4'b1000, out);
            $finish;
        end
        arg_0 = 8'b10111000;
        #0;
        if (4'b1001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 184", 4'b1001, out);
            $finish;
        end
        arg_0 = 8'b10111001;
        #0;
        if (4'b1010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 185", 4'b1010, out);
            $finish;
        end
        arg_0 = 8'b10111010;
        #0;
        if (4'b1011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 186", 4'b1011, out);
            $finish;
        end
        arg_0 = 8'b10111011;
        #0;
        if (4'b1100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 187", 4'b1100, out);
            $finish;
        end
        arg_0 = 8'b10111100;
        #0;
        if (4'b1101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 188", 4'b1101, out);
            $finish;
        end
        arg_0 = 8'b10111101;
        #0;
        if (4'b1110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 189", 4'b1110, out);
            $finish;
        end
        arg_0 = 8'b10111110;
        #0;
        if (4'b1111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 190", 4'b1111, out);
            $finish;
        end
        arg_0 = 8'b10111111;
        #0;
        if (4'b0000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 191", 4'b0000, out);
            $finish;
        end
        arg_0 = 8'b11000000;
        #0;
        if (4'b0001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 192", 4'b0001, out);
            $finish;
        end
        arg_0 = 8'b11000001;
        #0;
        if (4'b0010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 193", 4'b0010, out);
            $finish;
        end
        arg_0 = 8'b11000010;
        #0;
        if (4'b0011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 194", 4'b0011, out);
            $finish;
        end
        arg_0 = 8'b11000011;
        #0;
        if (4'b0100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 195", 4'b0100, out);
            $finish;
        end
        arg_0 = 8'b11000100;
        #0;
        if (4'b0101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 196", 4'b0101, out);
            $finish;
        end
        arg_0 = 8'b11000101;
        #0;
        if (4'b0110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 197", 4'b0110, out);
            $finish;
        end
        arg_0 = 8'b11000110;
        #0;
        if (4'b0111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 198", 4'b0111, out);
            $finish;
        end
        arg_0 = 8'b11000111;
        #0;
        if (4'b1000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 199", 4'b1000, out);
            $finish;
        end
        arg_0 = 8'b11001000;
        #0;
        if (4'b1001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 200", 4'b1001, out);
            $finish;
        end
        arg_0 = 8'b11001001;
        #0;
        if (4'b1010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 201", 4'b1010, out);
            $finish;
        end
        arg_0 = 8'b11001010;
        #0;
        if (4'b1011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 202", 4'b1011, out);
            $finish;
        end
        arg_0 = 8'b11001011;
        #0;
        if (4'b1100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 203", 4'b1100, out);
            $finish;
        end
        arg_0 = 8'b11001100;
        #0;
        if (4'b1101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 204", 4'b1101, out);
            $finish;
        end
        arg_0 = 8'b11001101;
        #0;
        if (4'b1110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 205", 4'b1110, out);
            $finish;
        end
        arg_0 = 8'b11001110;
        #0;
        if (4'b1111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 206", 4'b1111, out);
            $finish;
        end
        arg_0 = 8'b11001111;
        #0;
        if (4'b0000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 207", 4'b0000, out);
            $finish;
        end
        arg_0 = 8'b11010000;
        #0;
        if (4'b0001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 208", 4'b0001, out);
            $finish;
        end
        arg_0 = 8'b11010001;
        #0;
        if (4'b0010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 209", 4'b0010, out);
            $finish;
        end
        arg_0 = 8'b11010010;
        #0;
        if (4'b0011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 210", 4'b0011, out);
            $finish;
        end
        arg_0 = 8'b11010011;
        #0;
        if (4'b0100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 211", 4'b0100, out);
            $finish;
        end
        arg_0 = 8'b11010100;
        #0;
        if (4'b0101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 212", 4'b0101, out);
            $finish;
        end
        arg_0 = 8'b11010101;
        #0;
        if (4'b0110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 213", 4'b0110, out);
            $finish;
        end
        arg_0 = 8'b11010110;
        #0;
        if (4'b0111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 214", 4'b0111, out);
            $finish;
        end
        arg_0 = 8'b11010111;
        #0;
        if (4'b1000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 215", 4'b1000, out);
            $finish;
        end
        arg_0 = 8'b11011000;
        #0;
        if (4'b1001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 216", 4'b1001, out);
            $finish;
        end
        arg_0 = 8'b11011001;
        #0;
        if (4'b1010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 217", 4'b1010, out);
            $finish;
        end
        arg_0 = 8'b11011010;
        #0;
        if (4'b1011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 218", 4'b1011, out);
            $finish;
        end
        arg_0 = 8'b11011011;
        #0;
        if (4'b1100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 219", 4'b1100, out);
            $finish;
        end
        arg_0 = 8'b11011100;
        #0;
        if (4'b1101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 220", 4'b1101, out);
            $finish;
        end
        arg_0 = 8'b11011101;
        #0;
        if (4'b1110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 221", 4'b1110, out);
            $finish;
        end
        arg_0 = 8'b11011110;
        #0;
        if (4'b1111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 222", 4'b1111, out);
            $finish;
        end
        arg_0 = 8'b11011111;
        #0;
        if (4'b0000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 223", 4'b0000, out);
            $finish;
        end
        arg_0 = 8'b11100000;
        #0;
        if (4'b0001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 224", 4'b0001, out);
            $finish;
        end
        arg_0 = 8'b11100001;
        #0;
        if (4'b0010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 225", 4'b0010, out);
            $finish;
        end
        arg_0 = 8'b11100010;
        #0;
        if (4'b0011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 226", 4'b0011, out);
            $finish;
        end
        arg_0 = 8'b11100011;
        #0;
        if (4'b0100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 227", 4'b0100, out);
            $finish;
        end
        arg_0 = 8'b11100100;
        #0;
        if (4'b0101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 228", 4'b0101, out);
            $finish;
        end
        arg_0 = 8'b11100101;
        #0;
        if (4'b0110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 229", 4'b0110, out);
            $finish;
        end
        arg_0 = 8'b11100110;
        #0;
        if (4'b0111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 230", 4'b0111, out);
            $finish;
        end
        arg_0 = 8'b11100111;
        #0;
        if (4'b1000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 231", 4'b1000, out);
            $finish;
        end
        arg_0 = 8'b11101000;
        #0;
        if (4'b1001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 232", 4'b1001, out);
            $finish;
        end
        arg_0 = 8'b11101001;
        #0;
        if (4'b1010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 233", 4'b1010, out);
            $finish;
        end
        arg_0 = 8'b11101010;
        #0;
        if (4'b1011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 234", 4'b1011, out);
            $finish;
        end
        arg_0 = 8'b11101011;
        #0;
        if (4'b1100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 235", 4'b1100, out);
            $finish;
        end
        arg_0 = 8'b11101100;
        #0;
        if (4'b1101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 236", 4'b1101, out);
            $finish;
        end
        arg_0 = 8'b11101101;
        #0;
        if (4'b1110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 237", 4'b1110, out);
            $finish;
        end
        arg_0 = 8'b11101110;
        #0;
        if (4'b1111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 238", 4'b1111, out);
            $finish;
        end
        arg_0 = 8'b11101111;
        #0;
        if (4'b0000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 239", 4'b0000, out);
            $finish;
        end
        arg_0 = 8'b11110000;
        #0;
        if (4'b0001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 240", 4'b0001, out);
            $finish;
        end
        arg_0 = 8'b11110001;
        #0;
        if (4'b0010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 241", 4'b0010, out);
            $finish;
        end
        arg_0 = 8'b11110010;
        #0;
        if (4'b0011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 242", 4'b0011, out);
            $finish;
        end
        arg_0 = 8'b11110011;
        #0;
        if (4'b0100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 243", 4'b0100, out);
            $finish;
        end
        arg_0 = 8'b11110100;
        #0;
        if (4'b0101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 244", 4'b0101, out);
            $finish;
        end
        arg_0 = 8'b11110101;
        #0;
        if (4'b0110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 245", 4'b0110, out);
            $finish;
        end
        arg_0 = 8'b11110110;
        #0;
        if (4'b0111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 246", 4'b0111, out);
            $finish;
        end
        arg_0 = 8'b11110111;
        #0;
        if (4'b1000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 247", 4'b1000, out);
            $finish;
        end
        arg_0 = 8'b11111000;
        #0;
        if (4'b1001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 248", 4'b1001, out);
            $finish;
        end
        arg_0 = 8'b11111001;
        #0;
        if (4'b1010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 249", 4'b1010, out);
            $finish;
        end
        arg_0 = 8'b11111010;
        #0;
        if (4'b1011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 250", 4'b1011, out);
            $finish;
        end
        arg_0 = 8'b11111011;
        #0;
        if (4'b1100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 251", 4'b1100, out);
            $finish;
        end
        arg_0 = 8'b11111100;
        #0;
        if (4'b1101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 252", 4'b1101, out);
            $finish;
        end
        arg_0 = 8'b11111101;
        #0;
        if (4'b1110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 253", 4'b1110, out);
            $finish;
        end
        arg_0 = 8'b11111110;
        #0;
        if (4'b1111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 254", 4'b1111, out);
            $finish;
        end
        arg_0 = 8'b11111111;
        #0;
        if (4'b0000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 255", 4'b0000, out);
            $finish;
        end
        $display("TESTBENCH OK", );
        $finish;
    end
endmodule
//
module dut(input wire [7:0] arg_0, output reg [3:0] out);
    reg [0:0] r0;
    reg [0:0] r1;
    reg [0:0] r2;
    reg [0:0] r3;
    reg [0:0] r4;
    reg [0:0] r5;
    reg [0:0] r6;
    reg [0:0] r7;
    reg [0:0] r8;
    reg [0:0] r9;
    reg [0:0] r10;
    reg [0:0] r11;
    reg [0:0] r12;
    reg [0:0] r13;
    reg [0:0] r14;
    reg [0:0] r15;
    always @(*) begin
        r0 = arg_0[0];
        r1 = arg_0[1];
        r2 = arg_0[2];
        r3 = arg_0[3];
        r4 = arg_0[4];
        r5 = arg_0[5];
        r6 = arg_0[6];
        r7 = arg_0[7];
        // let a = a.val();
        //
        // let b = a + 1;
        //
        // let c = b.resize();
        //
        // signal(c)
        //
        { r15,r14,r13,r12,r11,r10,r9,r8 } = { r7, r6, r5, r4, r3, r2, r1, r0 } + { 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b1 };
        out = { r11, r10, r9, r8 };
    end
endmodule
