//! I²S (Inter-IC Sound) transmitter (master mode, left-justified)
//!
//! I²S is Philips' 1986 chip-to-chip digital-audio standard, the
//! universal link between a host (CPU / FPGA) and an audio codec
//! (CS43L22 / WM8731 / ES9038 / AK4490 / a thousand others).
//! Three wires carry stereo audio:
//!
//! - `BCLK` — bit clock, generated by the master.
//! - `LRCK` — left / right select, equals the audio *sample rate*
//!   (one full LRCK cycle = one stereo sample = `2 × N` BCLK
//!   cycles for `N`-bit samples).  `LRCK = 0` ⇒ left channel is
//!   active; `LRCK = 1` ⇒ right channel.
//! - `SD` — serial data, MSB-first, two's-complement signed
//!   integer.
//!
//! **v1 scope:** *master mode, transmit-only, 16-bit, left-
//! justified framing*.  Left-justified means the first data bit
//! appears on the *same* BCLK edge as the LRCK transition (no
//! one-bit delay).  Most codecs accept LJ as an alternative to
//! the canonical Philips framing; switching is a v2 enhancement
//! of the inner FSM.  The host strobes `bclk_tick` once per
//! BCLK half-period — this is the same decoupling pattern used
//! by [super::super::serial_bus::smpte_ltc_encoder::SmpteLtcEncoder].
//!
//! Composes [super::super::core::dff::DFF].  The host derives
//! `bclk_tick` from a divided board clock (e.g., 100 MHz ÷ 32 ≈
//! 3.125 MHz BCLK → 48 kHz × 32-bit-frame stereo).
//!
//! Here is the schematic symbol
#![doc = badascii_doc::badascii_formal!(r"
     +------------+I2sTx+----------+
     |                             |
S<16>|                             | bool
+--->| left_sample           bclk  +--->
S<16>|                             | bool
+--->| right_sample          lrck  +--->
bool |                             | bool
+--->| bclk_tick                sd +--->
bool |                             | bool
+--->| sample_load    sample_taken +--->
     +-----------------------------+
")]
//!
//!# Internals
//!
//! Two 16-bit shift registers (`l_shift`, `r_shift`).  A 5-bit
//! bit counter `bit_idx` counts 0..32 — one full stereo sample.
//! The tick FSM has two states (`BclkLow / BclkHigh`); each
//! `bclk_tick` advances by one half-period:
//!
//! - `BclkLow → BclkHigh` (rising edge): slave samples SD.
//! - `BclkHigh → BclkLow` (falling edge): master shifts the
//!   active register one position; updates `bit_idx`.  When
//!   `bit_idx` rolls from 31 → 0, LRCK transitions and the
//!   shift registers reload from the latched sample inputs.
//!
//!# Example
//!
//!```
#![doc = include_str!("../../examples/i2s_tx.rs")]
//!```
//!
//! The trace below demonstrates the result.
#![doc = include_str!("../../doc/i2s_tx.md")]
//!
//! And the auto-generated FSM diagram for the half-cell tick FSM:
#![doc = include_str!("../../doc/i2s_tx_fsm.md")]
use rhdl::core::fsm::analysis::Transition;
use rhdl::prelude::*;

use crate::core::dff;

/// Author-curated transition graph for the bit-clock tick FSM.
pub const FSM_TRANSITIONS: &[Transition] = &[
    Transition {
        source_index: 0,
        target_index: 1,
    },
    Transition {
        source_index: 1,
        target_index: 0,
    },
];

/// Bit-clock half-cell state.
#[derive(PartialEq, Debug, Digital, Clone, Copy, Default, Fsm)]
pub enum BclkPhase {
    /// BCLK low (master setting up next bit).
    #[default]
    #[fsm_state(label = "BCLK low")]
    BclkLow,
    /// BCLK high (slave samples).
    #[fsm_state(label = "BCLK high")]
    BclkHigh,
}

#[derive(Clone, Debug, Synchronous, SynchronousDQ, Default, FsmWidget)]
#[rhdl(dq_no_prefix)]
#[fsm(state_field = "phase", state_enum = BclkPhase)]
/// I²S transmitter (master mode, left-justified, 16-bit stereo).
pub struct I2sTx {
    phase: dff::DFF<BclkPhase>,
    /// Bit position within the current stereo sample (0..32).
    bit_idx: dff::DFF<Bits<6>>,
    /// L/R select (false = left, true = right).
    lrck_reg: dff::DFF<bool>,
    /// Active shift register for the channel currently being transmitted.
    /// Reloaded from `l_latched` / `r_latched` at each LRCK edge.
    shift: dff::DFF<Bits<16>>,
    /// Latched left sample (refreshed when host strobes `sample_load`).
    l_latched: dff::DFF<Bits<16>>,
    /// Latched right sample.
    r_latched: dff::DFF<Bits<16>>,
    /// One-cycle pulse: a fresh stereo sample was consumed on this LRCK edge.
    sample_taken_pulse: dff::DFF<bool>,
}

#[derive(PartialEq, Debug, Digital, Clone, Copy)]
/// Inputs to [I2sTx].
pub struct In {
    /// Left-channel signed audio sample (latched on `sample_load`).
    pub left_sample: SignedBits<16>,
    /// Right-channel signed audio sample (latched on `sample_load`).
    pub right_sample: SignedBits<16>,
    /// Strobe to advance one BCLK half-period.
    pub bclk_tick: bool,
    /// Strobe to load a fresh stereo sample into the latch.  Should pulse
    /// at least once per audio sample period.
    pub sample_load: bool,
}

#[derive(PartialEq, Debug, Digital, Clone, Copy)]
/// Outputs from [I2sTx].
pub struct Out {
    /// Bit clock (toggles per `bclk_tick`).
    pub bclk: bool,
    /// L/R select.  Low = left channel data on SD; high = right.
    pub lrck: bool,
    /// Serial data — MSB of the active shift register.
    pub sd: bool,
    /// Pulses for one cycle when the latched stereo sample is consumed
    /// (i.e., a new sample is needed).
    pub sample_taken: bool,
}

impl SynchronousIO for I2sTx {
    type I = In;
    type O = Out;
    type Kernel = i2s_tx;
}

#[kernel]
/// Kernel for [I2sTx].
pub fn i2s_tx(cr: ClockReset, i: In, q: Q) -> (Out, D) {
    let mut d = D::dont_care();
    d.phase = q.phase;
    d.bit_idx = q.bit_idx;
    d.lrck_reg = q.lrck_reg;
    d.shift = q.shift;
    d.l_latched = q.l_latched;
    d.r_latched = q.r_latched;
    d.sample_taken_pulse = false;

    if i.sample_load {
        d.l_latched = i.left_sample.as_unsigned();
        d.r_latched = i.right_sample.as_unsigned();
    }

    if i.bclk_tick {
        match q.phase {
            BclkPhase::BclkLow => {
                // Rising edge — slave latches.  No internal change beyond
                // moving to BclkHigh.
                d.phase = BclkPhase::BclkHigh;
            }
            BclkPhase::BclkHigh => {
                // Falling edge — shift one bit out, update bit_idx, possibly
                // transition LRCK and reload the shift register.
                d.shift = q.shift << bits::<16>(1);
                if q.bit_idx == bits::<6>(31) {
                    // End of stereo frame: roll bit_idx, toggle LRCK, reload.
                    d.bit_idx = bits::<6>(0);
                    let new_lrck = !q.lrck_reg;
                    d.lrck_reg = new_lrck;
                    if new_lrck {
                        // Switching to right channel.
                        d.shift = q.r_latched;
                    } else {
                        // Switching to left channel — the host should reload
                        // before this point; pulse sample_taken to nudge.
                        d.shift = q.l_latched;
                        d.sample_taken_pulse = true;
                    }
                } else if q.bit_idx == bits::<6>(15) {
                    // Mid-frame: switch from left half to right half.
                    d.bit_idx = q.bit_idx + bits::<6>(1);
                    d.lrck_reg = true;
                    d.shift = q.r_latched;
                } else {
                    d.bit_idx = q.bit_idx + bits::<6>(1);
                }
                d.phase = BclkPhase::BclkLow;
            }
        }
    }

    if cr.reset.any() {
        d.phase = BclkPhase::BclkLow;
        d.bit_idx = bits::<6>(0);
        d.lrck_reg = false;
        d.shift = bits::<16>(0);
        d.l_latched = bits::<16>(0);
        d.r_latched = bits::<16>(0);
        d.sample_taken_pulse = false;
    }

    let bclk = match q.phase {
        BclkPhase::BclkHigh => true,
        BclkPhase::BclkLow => false,
    };

    let mut o = Out::dont_care();
    o.bclk = bclk;
    o.lrck = q.lrck_reg;
    o.sd = (q.shift & bits::<16>(0x8000)) != bits::<16>(0);
    o.sample_taken = q.sample_taken_pulse;
    (o, d)
}

#[cfg(test)]
mod tests {
    use super::*;
    use expect_test::expect;
    use std::path::PathBuf;

    fn idle_in() -> In {
        In {
            left_sample: signed(0),
            right_sample: signed(0),
            bclk_tick: false,
            sample_load: false,
        }
    }

    /// Drive a sequence: load a stereo sample, then run N bclk_ticks.
    fn drive_with_sample(left: i16, right: i16, ticks: usize) -> Vec<In> {
        let mut out = Vec::with_capacity(ticks + 4);
        out.push(In {
            left_sample: signed(left as i128),
            right_sample: signed(right as i128),
            bclk_tick: false,
            sample_load: true,
        });
        out.push(idle_in());
        for _ in 0..ticks {
            out.push(In {
                left_sample: signed(0),
                right_sample: signed(0),
                bclk_tick: true,
                sample_load: false,
            });
            out.push(idle_in());
        }
        out
    }

    #[test]
    fn test_idle_no_bclk_toggles() -> miette::Result<()> {
        let uut = I2sTx::default();
        let stream = std::iter::repeat_n(idle_in(), 32)
            .with_reset(1)
            .clock_pos_edge(100);
        let outputs: Vec<_> = uut
            .run(stream)
            .synchronous_sample()
            .filter(|s| !s.input.0.reset.any())
            .collect();
        let any_high = outputs.iter().any(|s| s.output.bclk);
        assert!(!any_high);
        Ok(())
    }

    #[test]
    fn test_one_full_frame_yields_lrck_toggle() -> miette::Result<()> {
        // 32 bits per frame × 2 ticks per bit = 64 ticks for one full LRCK cycle.
        let uut = I2sTx::default();
        let stream_in = drive_with_sample(0x1234, 0x5678, 80);
        let stream = stream_in.into_iter().with_reset(1).clock_pos_edge(100);
        let outputs: Vec<_> = uut
            .run(stream)
            .synchronous_sample()
            .filter(|s| !s.input.0.reset.any())
            .collect();
        // Count LRCK transitions; should be at least 2 (low→high mid-frame,
        // high→low at end of frame).
        let mut transitions = 0;
        for w in outputs.windows(2) {
            if w[0].output.lrck != w[1].output.lrck {
                transitions += 1;
            }
        }
        assert!(transitions >= 2, "got {transitions} LRCK transitions");
        Ok(())
    }

    #[test]
    fn test_sample_taken_pulses() -> miette::Result<()> {
        let uut = I2sTx::default();
        let stream_in = drive_with_sample(0x1234, 0x5678, 200);
        let stream = stream_in.into_iter().with_reset(1).clock_pos_edge(100);
        let any_taken = uut
            .run(stream)
            .synchronous_sample()
            .filter(|s| !s.input.0.reset.any())
            .any(|s| s.output.sample_taken);
        assert!(any_taken);
        Ok(())
    }

    #[test]
    fn test_vlog_generation() -> miette::Result<()> {
        let uut = I2sTx::default();
        let desc = uut.descriptor("top".into())?;
        let hdl = desc.hdl()?.modules.pretty();
        let expect = expect!["10422"];
        expect.assert_eq(&hdl.len().to_string());
        Ok(())
    }

    #[test]
    fn test_i2s_tx_hdl_works() -> miette::Result<()> {
        let uut = I2sTx::default();
        let stream_in = drive_with_sample(0x1234, 0x5678, 80);
        let stream = stream_in.into_iter().with_reset(1).clock_pos_edge(100);
        let test_bench = uut.run(stream).collect::<SynchronousTestBench<_, _>>();
        let tm = test_bench.rtl(&uut, &Default::default())?;
        tm.run_iverilog()?;
        Ok(())
    }

    #[test]
    fn test_i2s_tx_trace() -> miette::Result<()> {
        let uut = I2sTx::default();
        let stream_in = drive_with_sample(0x1234, 0x5678, 80);
        let stream = stream_in.into_iter().with_reset(1).clock_pos_edge(100);
        let vcd = uut.run(stream).collect::<VcdFile>();
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("vcd")
            .join("i2s_tx");
        std::fs::create_dir_all(&root).unwrap();
        let expect = expect!["2f70376655b67602e7bed82cc2dd3a93e85e5b8dab61fccd58419ade0c177e4e"];
        let digest = vcd.dump_to_file(root.join("i2s_tx.vcd")).unwrap();
        expect.assert_eq(&digest);
        Ok(())
    }

    #[test]
    fn test_fsm_descriptor_round_trip() {
        let desc = I2sTx::fsm_descriptor();
        assert_eq!(desc.widget_name, "I2sTx");
        assert_eq!(desc.variants().len(), 2);
        assert_eq!(desc.initial_index(), 0);
    }
}
