mod digital;
mod utils;
pub use digital::derive_digital;
mod digital_enum;
mod kernel;
pub use kernel::hdl_kernel;
mod circuit;
pub use circuit::derive_circuit;
mod circuit_dq;
pub use circuit_dq::derive_circuit_dq;
mod timed;
pub use timed::derive_timed;
mod synchronous;
pub use synchronous::derive_synchronous;
mod synchronous_dq;
pub use synchronous_dq::derive_synchronous_dq;
mod export;
pub use export::export_macro;
mod path;
pub use path::path_macro;
pub mod vlog;
pub use vlog::modules;
