// Autogenerated testbench for kernel_do_stuff
module testbench();
    wire [19:0] out;
    reg [3:0] arg_0;
    reg [3:0] arg_1;
    assign out = kernel_do_stuff(arg_0, arg_1);
    initial begin
        arg_0 = 4'b0000;
        arg_1 = 4'b0000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 0", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0000;
        arg_1 = 4'b0001;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 1", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0000;
        arg_1 = 4'b0010;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 2", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0000;
        arg_1 = 4'b0011;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 3", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0000;
        arg_1 = 4'b0100;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 4", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0000;
        arg_1 = 4'b0101;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 5", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0000;
        arg_1 = 4'b0110;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 6", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0000;
        arg_1 = 4'b0111;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 7", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0000;
        arg_1 = 4'b1000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 8", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0000;
        arg_1 = 4'b1001;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 9", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0000;
        arg_1 = 4'b1010;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 10", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0000;
        arg_1 = 4'b1011;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 11", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0000;
        arg_1 = 4'b1100;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 12", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0000;
        arg_1 = 4'b1101;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 13", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0000;
        arg_1 = 4'b1110;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 14", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0000;
        arg_1 = 4'b1111;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 15", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0001;
        arg_1 = 4'b0000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 16", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0001;
        arg_1 = 4'b0001;
        #0;
        if (20'b00010001000100010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 17", 20'b00010001000100010001, out);
            $finish;
        end
        arg_0 = 4'b0001;
        arg_1 = 4'b0010;
        #0;
        if (20'b00100010001000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 18", 20'b00100010001000100010, out);
            $finish;
        end
        arg_0 = 4'b0001;
        arg_1 = 4'b0011;
        #0;
        if (20'b00110011001100110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 19", 20'b00110011001100110011, out);
            $finish;
        end
        arg_0 = 4'b0001;
        arg_1 = 4'b0100;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 20", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b0001;
        arg_1 = 4'b0101;
        #0;
        if (20'b01010101010101010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 21", 20'b01010101010101010101, out);
            $finish;
        end
        arg_0 = 4'b0001;
        arg_1 = 4'b0110;
        #0;
        if (20'b01100110011001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 22", 20'b01100110011001100110, out);
            $finish;
        end
        arg_0 = 4'b0001;
        arg_1 = 4'b0111;
        #0;
        if (20'b01110111011101110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 23", 20'b01110111011101110111, out);
            $finish;
        end
        arg_0 = 4'b0001;
        arg_1 = 4'b1000;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 24", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b0001;
        arg_1 = 4'b1001;
        #0;
        if (20'b10011001100110011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 25", 20'b10011001100110011001, out);
            $finish;
        end
        arg_0 = 4'b0001;
        arg_1 = 4'b1010;
        #0;
        if (20'b10101010101010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 26", 20'b10101010101010101010, out);
            $finish;
        end
        arg_0 = 4'b0001;
        arg_1 = 4'b1011;
        #0;
        if (20'b10111011101110111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 27", 20'b10111011101110111011, out);
            $finish;
        end
        arg_0 = 4'b0001;
        arg_1 = 4'b1100;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 28", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b0001;
        arg_1 = 4'b1101;
        #0;
        if (20'b11011101110111011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 29", 20'b11011101110111011101, out);
            $finish;
        end
        arg_0 = 4'b0001;
        arg_1 = 4'b1110;
        #0;
        if (20'b11101110111011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 30", 20'b11101110111011101110, out);
            $finish;
        end
        arg_0 = 4'b0001;
        arg_1 = 4'b1111;
        #0;
        if (20'b11111111111111111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 31", 20'b11111111111111111111, out);
            $finish;
        end
        arg_0 = 4'b0010;
        arg_1 = 4'b0000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 32", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0010;
        arg_1 = 4'b0001;
        #0;
        if (20'b00100010001000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 33", 20'b00100010001000100010, out);
            $finish;
        end
        arg_0 = 4'b0010;
        arg_1 = 4'b0010;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 34", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b0010;
        arg_1 = 4'b0011;
        #0;
        if (20'b01100110011001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 35", 20'b01100110011001100110, out);
            $finish;
        end
        arg_0 = 4'b0010;
        arg_1 = 4'b0100;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 36", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b0010;
        arg_1 = 4'b0101;
        #0;
        if (20'b10101010101010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 37", 20'b10101010101010101010, out);
            $finish;
        end
        arg_0 = 4'b0010;
        arg_1 = 4'b0110;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 38", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b0010;
        arg_1 = 4'b0111;
        #0;
        if (20'b11101110111011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 39", 20'b11101110111011101110, out);
            $finish;
        end
        arg_0 = 4'b0010;
        arg_1 = 4'b1000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 40", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0010;
        arg_1 = 4'b1001;
        #0;
        if (20'b00100010001000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 41", 20'b00100010001000100010, out);
            $finish;
        end
        arg_0 = 4'b0010;
        arg_1 = 4'b1010;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 42", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b0010;
        arg_1 = 4'b1011;
        #0;
        if (20'b01100110011001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 43", 20'b01100110011001100110, out);
            $finish;
        end
        arg_0 = 4'b0010;
        arg_1 = 4'b1100;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 44", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b0010;
        arg_1 = 4'b1101;
        #0;
        if (20'b10101010101010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 45", 20'b10101010101010101010, out);
            $finish;
        end
        arg_0 = 4'b0010;
        arg_1 = 4'b1110;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 46", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b0010;
        arg_1 = 4'b1111;
        #0;
        if (20'b11101110111011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 47", 20'b11101110111011101110, out);
            $finish;
        end
        arg_0 = 4'b0011;
        arg_1 = 4'b0000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 48", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0011;
        arg_1 = 4'b0001;
        #0;
        if (20'b00110011001100110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 49", 20'b00110011001100110011, out);
            $finish;
        end
        arg_0 = 4'b0011;
        arg_1 = 4'b0010;
        #0;
        if (20'b01100110011001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 50", 20'b01100110011001100110, out);
            $finish;
        end
        arg_0 = 4'b0011;
        arg_1 = 4'b0011;
        #0;
        if (20'b10011001100110011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 51", 20'b10011001100110011001, out);
            $finish;
        end
        arg_0 = 4'b0011;
        arg_1 = 4'b0100;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 52", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b0011;
        arg_1 = 4'b0101;
        #0;
        if (20'b11111111111111111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 53", 20'b11111111111111111111, out);
            $finish;
        end
        arg_0 = 4'b0011;
        arg_1 = 4'b0110;
        #0;
        if (20'b00100010001000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 54", 20'b00100010001000100010, out);
            $finish;
        end
        arg_0 = 4'b0011;
        arg_1 = 4'b0111;
        #0;
        if (20'b01010101010101010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 55", 20'b01010101010101010101, out);
            $finish;
        end
        arg_0 = 4'b0011;
        arg_1 = 4'b1000;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 56", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b0011;
        arg_1 = 4'b1001;
        #0;
        if (20'b10111011101110111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 57", 20'b10111011101110111011, out);
            $finish;
        end
        arg_0 = 4'b0011;
        arg_1 = 4'b1010;
        #0;
        if (20'b11101110111011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 58", 20'b11101110111011101110, out);
            $finish;
        end
        arg_0 = 4'b0011;
        arg_1 = 4'b1011;
        #0;
        if (20'b00010001000100010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 59", 20'b00010001000100010001, out);
            $finish;
        end
        arg_0 = 4'b0011;
        arg_1 = 4'b1100;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 60", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b0011;
        arg_1 = 4'b1101;
        #0;
        if (20'b01110111011101110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 61", 20'b01110111011101110111, out);
            $finish;
        end
        arg_0 = 4'b0011;
        arg_1 = 4'b1110;
        #0;
        if (20'b10101010101010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 62", 20'b10101010101010101010, out);
            $finish;
        end
        arg_0 = 4'b0011;
        arg_1 = 4'b1111;
        #0;
        if (20'b11011101110111011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 63", 20'b11011101110111011101, out);
            $finish;
        end
        arg_0 = 4'b0100;
        arg_1 = 4'b0000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 64", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0100;
        arg_1 = 4'b0001;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 65", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b0100;
        arg_1 = 4'b0010;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 66", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b0100;
        arg_1 = 4'b0011;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 67", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b0100;
        arg_1 = 4'b0100;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 68", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0100;
        arg_1 = 4'b0101;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 69", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b0100;
        arg_1 = 4'b0110;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 70", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b0100;
        arg_1 = 4'b0111;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 71", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b0100;
        arg_1 = 4'b1000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 72", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0100;
        arg_1 = 4'b1001;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 73", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b0100;
        arg_1 = 4'b1010;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 74", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b0100;
        arg_1 = 4'b1011;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 75", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b0100;
        arg_1 = 4'b1100;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 76", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0100;
        arg_1 = 4'b1101;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 77", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b0100;
        arg_1 = 4'b1110;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 78", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b0100;
        arg_1 = 4'b1111;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 79", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b0101;
        arg_1 = 4'b0000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 80", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0101;
        arg_1 = 4'b0001;
        #0;
        if (20'b01010101010101010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 81", 20'b01010101010101010101, out);
            $finish;
        end
        arg_0 = 4'b0101;
        arg_1 = 4'b0010;
        #0;
        if (20'b10101010101010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 82", 20'b10101010101010101010, out);
            $finish;
        end
        arg_0 = 4'b0101;
        arg_1 = 4'b0011;
        #0;
        if (20'b11111111111111111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 83", 20'b11111111111111111111, out);
            $finish;
        end
        arg_0 = 4'b0101;
        arg_1 = 4'b0100;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 84", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b0101;
        arg_1 = 4'b0101;
        #0;
        if (20'b10011001100110011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 85", 20'b10011001100110011001, out);
            $finish;
        end
        arg_0 = 4'b0101;
        arg_1 = 4'b0110;
        #0;
        if (20'b11101110111011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 86", 20'b11101110111011101110, out);
            $finish;
        end
        arg_0 = 4'b0101;
        arg_1 = 4'b0111;
        #0;
        if (20'b00110011001100110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 87", 20'b00110011001100110011, out);
            $finish;
        end
        arg_0 = 4'b0101;
        arg_1 = 4'b1000;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 88", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b0101;
        arg_1 = 4'b1001;
        #0;
        if (20'b11011101110111011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 89", 20'b11011101110111011101, out);
            $finish;
        end
        arg_0 = 4'b0101;
        arg_1 = 4'b1010;
        #0;
        if (20'b00100010001000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 90", 20'b00100010001000100010, out);
            $finish;
        end
        arg_0 = 4'b0101;
        arg_1 = 4'b1011;
        #0;
        if (20'b01110111011101110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 91", 20'b01110111011101110111, out);
            $finish;
        end
        arg_0 = 4'b0101;
        arg_1 = 4'b1100;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 92", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b0101;
        arg_1 = 4'b1101;
        #0;
        if (20'b00010001000100010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 93", 20'b00010001000100010001, out);
            $finish;
        end
        arg_0 = 4'b0101;
        arg_1 = 4'b1110;
        #0;
        if (20'b01100110011001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 94", 20'b01100110011001100110, out);
            $finish;
        end
        arg_0 = 4'b0101;
        arg_1 = 4'b1111;
        #0;
        if (20'b10111011101110111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 95", 20'b10111011101110111011, out);
            $finish;
        end
        arg_0 = 4'b0110;
        arg_1 = 4'b0000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 96", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0110;
        arg_1 = 4'b0001;
        #0;
        if (20'b01100110011001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 97", 20'b01100110011001100110, out);
            $finish;
        end
        arg_0 = 4'b0110;
        arg_1 = 4'b0010;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 98", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b0110;
        arg_1 = 4'b0011;
        #0;
        if (20'b00100010001000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 99", 20'b00100010001000100010, out);
            $finish;
        end
        arg_0 = 4'b0110;
        arg_1 = 4'b0100;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 100", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b0110;
        arg_1 = 4'b0101;
        #0;
        if (20'b11101110111011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 101", 20'b11101110111011101110, out);
            $finish;
        end
        arg_0 = 4'b0110;
        arg_1 = 4'b0110;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 102", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b0110;
        arg_1 = 4'b0111;
        #0;
        if (20'b10101010101010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 103", 20'b10101010101010101010, out);
            $finish;
        end
        arg_0 = 4'b0110;
        arg_1 = 4'b1000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 104", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0110;
        arg_1 = 4'b1001;
        #0;
        if (20'b01100110011001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 105", 20'b01100110011001100110, out);
            $finish;
        end
        arg_0 = 4'b0110;
        arg_1 = 4'b1010;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 106", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b0110;
        arg_1 = 4'b1011;
        #0;
        if (20'b00100010001000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 107", 20'b00100010001000100010, out);
            $finish;
        end
        arg_0 = 4'b0110;
        arg_1 = 4'b1100;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 108", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b0110;
        arg_1 = 4'b1101;
        #0;
        if (20'b11101110111011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 109", 20'b11101110111011101110, out);
            $finish;
        end
        arg_0 = 4'b0110;
        arg_1 = 4'b1110;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 110", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b0110;
        arg_1 = 4'b1111;
        #0;
        if (20'b10101010101010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 111", 20'b10101010101010101010, out);
            $finish;
        end
        arg_0 = 4'b0111;
        arg_1 = 4'b0000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 112", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b0111;
        arg_1 = 4'b0001;
        #0;
        if (20'b01110111011101110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 113", 20'b01110111011101110111, out);
            $finish;
        end
        arg_0 = 4'b0111;
        arg_1 = 4'b0010;
        #0;
        if (20'b11101110111011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 114", 20'b11101110111011101110, out);
            $finish;
        end
        arg_0 = 4'b0111;
        arg_1 = 4'b0011;
        #0;
        if (20'b01010101010101010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 115", 20'b01010101010101010101, out);
            $finish;
        end
        arg_0 = 4'b0111;
        arg_1 = 4'b0100;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 116", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b0111;
        arg_1 = 4'b0101;
        #0;
        if (20'b00110011001100110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 117", 20'b00110011001100110011, out);
            $finish;
        end
        arg_0 = 4'b0111;
        arg_1 = 4'b0110;
        #0;
        if (20'b10101010101010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 118", 20'b10101010101010101010, out);
            $finish;
        end
        arg_0 = 4'b0111;
        arg_1 = 4'b0111;
        #0;
        if (20'b00010001000100010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 119", 20'b00010001000100010001, out);
            $finish;
        end
        arg_0 = 4'b0111;
        arg_1 = 4'b1000;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 120", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b0111;
        arg_1 = 4'b1001;
        #0;
        if (20'b11111111111111111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 121", 20'b11111111111111111111, out);
            $finish;
        end
        arg_0 = 4'b0111;
        arg_1 = 4'b1010;
        #0;
        if (20'b01100110011001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 122", 20'b01100110011001100110, out);
            $finish;
        end
        arg_0 = 4'b0111;
        arg_1 = 4'b1011;
        #0;
        if (20'b11011101110111011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 123", 20'b11011101110111011101, out);
            $finish;
        end
        arg_0 = 4'b0111;
        arg_1 = 4'b1100;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 124", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b0111;
        arg_1 = 4'b1101;
        #0;
        if (20'b10111011101110111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 125", 20'b10111011101110111011, out);
            $finish;
        end
        arg_0 = 4'b0111;
        arg_1 = 4'b1110;
        #0;
        if (20'b00100010001000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 126", 20'b00100010001000100010, out);
            $finish;
        end
        arg_0 = 4'b0111;
        arg_1 = 4'b1111;
        #0;
        if (20'b10011001100110011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 127", 20'b10011001100110011001, out);
            $finish;
        end
        arg_0 = 4'b1000;
        arg_1 = 4'b0000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 128", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1000;
        arg_1 = 4'b0001;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 129", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1000;
        arg_1 = 4'b0010;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 130", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1000;
        arg_1 = 4'b0011;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 131", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1000;
        arg_1 = 4'b0100;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 132", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1000;
        arg_1 = 4'b0101;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 133", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1000;
        arg_1 = 4'b0110;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 134", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1000;
        arg_1 = 4'b0111;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 135", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1000;
        arg_1 = 4'b1000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 136", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1000;
        arg_1 = 4'b1001;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 137", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1000;
        arg_1 = 4'b1010;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 138", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1000;
        arg_1 = 4'b1011;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 139", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1000;
        arg_1 = 4'b1100;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 140", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1000;
        arg_1 = 4'b1101;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 141", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1000;
        arg_1 = 4'b1110;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 142", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1000;
        arg_1 = 4'b1111;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 143", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1001;
        arg_1 = 4'b0000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 144", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1001;
        arg_1 = 4'b0001;
        #0;
        if (20'b10011001100110011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 145", 20'b10011001100110011001, out);
            $finish;
        end
        arg_0 = 4'b1001;
        arg_1 = 4'b0010;
        #0;
        if (20'b00100010001000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 146", 20'b00100010001000100010, out);
            $finish;
        end
        arg_0 = 4'b1001;
        arg_1 = 4'b0011;
        #0;
        if (20'b10111011101110111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 147", 20'b10111011101110111011, out);
            $finish;
        end
        arg_0 = 4'b1001;
        arg_1 = 4'b0100;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 148", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b1001;
        arg_1 = 4'b0101;
        #0;
        if (20'b11011101110111011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 149", 20'b11011101110111011101, out);
            $finish;
        end
        arg_0 = 4'b1001;
        arg_1 = 4'b0110;
        #0;
        if (20'b01100110011001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 150", 20'b01100110011001100110, out);
            $finish;
        end
        arg_0 = 4'b1001;
        arg_1 = 4'b0111;
        #0;
        if (20'b11111111111111111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 151", 20'b11111111111111111111, out);
            $finish;
        end
        arg_0 = 4'b1001;
        arg_1 = 4'b1000;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 152", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1001;
        arg_1 = 4'b1001;
        #0;
        if (20'b00010001000100010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 153", 20'b00010001000100010001, out);
            $finish;
        end
        arg_0 = 4'b1001;
        arg_1 = 4'b1010;
        #0;
        if (20'b10101010101010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 154", 20'b10101010101010101010, out);
            $finish;
        end
        arg_0 = 4'b1001;
        arg_1 = 4'b1011;
        #0;
        if (20'b00110011001100110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 155", 20'b00110011001100110011, out);
            $finish;
        end
        arg_0 = 4'b1001;
        arg_1 = 4'b1100;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 156", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b1001;
        arg_1 = 4'b1101;
        #0;
        if (20'b01010101010101010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 157", 20'b01010101010101010101, out);
            $finish;
        end
        arg_0 = 4'b1001;
        arg_1 = 4'b1110;
        #0;
        if (20'b11101110111011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 158", 20'b11101110111011101110, out);
            $finish;
        end
        arg_0 = 4'b1001;
        arg_1 = 4'b1111;
        #0;
        if (20'b01110111011101110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 159", 20'b01110111011101110111, out);
            $finish;
        end
        arg_0 = 4'b1010;
        arg_1 = 4'b0000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 160", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1010;
        arg_1 = 4'b0001;
        #0;
        if (20'b10101010101010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 161", 20'b10101010101010101010, out);
            $finish;
        end
        arg_0 = 4'b1010;
        arg_1 = 4'b0010;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 162", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b1010;
        arg_1 = 4'b0011;
        #0;
        if (20'b11101110111011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 163", 20'b11101110111011101110, out);
            $finish;
        end
        arg_0 = 4'b1010;
        arg_1 = 4'b0100;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 164", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1010;
        arg_1 = 4'b0101;
        #0;
        if (20'b00100010001000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 165", 20'b00100010001000100010, out);
            $finish;
        end
        arg_0 = 4'b1010;
        arg_1 = 4'b0110;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 166", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b1010;
        arg_1 = 4'b0111;
        #0;
        if (20'b01100110011001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 167", 20'b01100110011001100110, out);
            $finish;
        end
        arg_0 = 4'b1010;
        arg_1 = 4'b1000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 168", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1010;
        arg_1 = 4'b1001;
        #0;
        if (20'b10101010101010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 169", 20'b10101010101010101010, out);
            $finish;
        end
        arg_0 = 4'b1010;
        arg_1 = 4'b1010;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 170", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b1010;
        arg_1 = 4'b1011;
        #0;
        if (20'b11101110111011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 171", 20'b11101110111011101110, out);
            $finish;
        end
        arg_0 = 4'b1010;
        arg_1 = 4'b1100;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 172", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1010;
        arg_1 = 4'b1101;
        #0;
        if (20'b00100010001000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 173", 20'b00100010001000100010, out);
            $finish;
        end
        arg_0 = 4'b1010;
        arg_1 = 4'b1110;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 174", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b1010;
        arg_1 = 4'b1111;
        #0;
        if (20'b01100110011001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 175", 20'b01100110011001100110, out);
            $finish;
        end
        arg_0 = 4'b1011;
        arg_1 = 4'b0000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 176", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1011;
        arg_1 = 4'b0001;
        #0;
        if (20'b10111011101110111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 177", 20'b10111011101110111011, out);
            $finish;
        end
        arg_0 = 4'b1011;
        arg_1 = 4'b0010;
        #0;
        if (20'b01100110011001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 178", 20'b01100110011001100110, out);
            $finish;
        end
        arg_0 = 4'b1011;
        arg_1 = 4'b0011;
        #0;
        if (20'b00010001000100010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 179", 20'b00010001000100010001, out);
            $finish;
        end
        arg_0 = 4'b1011;
        arg_1 = 4'b0100;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 180", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b1011;
        arg_1 = 4'b0101;
        #0;
        if (20'b01110111011101110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 181", 20'b01110111011101110111, out);
            $finish;
        end
        arg_0 = 4'b1011;
        arg_1 = 4'b0110;
        #0;
        if (20'b00100010001000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 182", 20'b00100010001000100010, out);
            $finish;
        end
        arg_0 = 4'b1011;
        arg_1 = 4'b0111;
        #0;
        if (20'b11011101110111011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 183", 20'b11011101110111011101, out);
            $finish;
        end
        arg_0 = 4'b1011;
        arg_1 = 4'b1000;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 184", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1011;
        arg_1 = 4'b1001;
        #0;
        if (20'b00110011001100110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 185", 20'b00110011001100110011, out);
            $finish;
        end
        arg_0 = 4'b1011;
        arg_1 = 4'b1010;
        #0;
        if (20'b11101110111011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 186", 20'b11101110111011101110, out);
            $finish;
        end
        arg_0 = 4'b1011;
        arg_1 = 4'b1011;
        #0;
        if (20'b10011001100110011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 187", 20'b10011001100110011001, out);
            $finish;
        end
        arg_0 = 4'b1011;
        arg_1 = 4'b1100;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 188", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b1011;
        arg_1 = 4'b1101;
        #0;
        if (20'b11111111111111111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 189", 20'b11111111111111111111, out);
            $finish;
        end
        arg_0 = 4'b1011;
        arg_1 = 4'b1110;
        #0;
        if (20'b10101010101010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 190", 20'b10101010101010101010, out);
            $finish;
        end
        arg_0 = 4'b1011;
        arg_1 = 4'b1111;
        #0;
        if (20'b01010101010101010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 191", 20'b01010101010101010101, out);
            $finish;
        end
        arg_0 = 4'b1100;
        arg_1 = 4'b0000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 192", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1100;
        arg_1 = 4'b0001;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 193", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b1100;
        arg_1 = 4'b0010;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 194", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1100;
        arg_1 = 4'b0011;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 195", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b1100;
        arg_1 = 4'b0100;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 196", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1100;
        arg_1 = 4'b0101;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 197", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b1100;
        arg_1 = 4'b0110;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 198", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1100;
        arg_1 = 4'b0111;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 199", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b1100;
        arg_1 = 4'b1000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 200", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1100;
        arg_1 = 4'b1001;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 201", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b1100;
        arg_1 = 4'b1010;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 202", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1100;
        arg_1 = 4'b1011;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 203", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b1100;
        arg_1 = 4'b1100;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 204", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1100;
        arg_1 = 4'b1101;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 205", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b1100;
        arg_1 = 4'b1110;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 206", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1100;
        arg_1 = 4'b1111;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 207", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b1101;
        arg_1 = 4'b0000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 208", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1101;
        arg_1 = 4'b0001;
        #0;
        if (20'b11011101110111011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 209", 20'b11011101110111011101, out);
            $finish;
        end
        arg_0 = 4'b1101;
        arg_1 = 4'b0010;
        #0;
        if (20'b10101010101010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 210", 20'b10101010101010101010, out);
            $finish;
        end
        arg_0 = 4'b1101;
        arg_1 = 4'b0011;
        #0;
        if (20'b01110111011101110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 211", 20'b01110111011101110111, out);
            $finish;
        end
        arg_0 = 4'b1101;
        arg_1 = 4'b0100;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 212", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b1101;
        arg_1 = 4'b0101;
        #0;
        if (20'b00010001000100010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 213", 20'b00010001000100010001, out);
            $finish;
        end
        arg_0 = 4'b1101;
        arg_1 = 4'b0110;
        #0;
        if (20'b11101110111011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 214", 20'b11101110111011101110, out);
            $finish;
        end
        arg_0 = 4'b1101;
        arg_1 = 4'b0111;
        #0;
        if (20'b10111011101110111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 215", 20'b10111011101110111011, out);
            $finish;
        end
        arg_0 = 4'b1101;
        arg_1 = 4'b1000;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 216", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1101;
        arg_1 = 4'b1001;
        #0;
        if (20'b01010101010101010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 217", 20'b01010101010101010101, out);
            $finish;
        end
        arg_0 = 4'b1101;
        arg_1 = 4'b1010;
        #0;
        if (20'b00100010001000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 218", 20'b00100010001000100010, out);
            $finish;
        end
        arg_0 = 4'b1101;
        arg_1 = 4'b1011;
        #0;
        if (20'b11111111111111111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 219", 20'b11111111111111111111, out);
            $finish;
        end
        arg_0 = 4'b1101;
        arg_1 = 4'b1100;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 220", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b1101;
        arg_1 = 4'b1101;
        #0;
        if (20'b10011001100110011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 221", 20'b10011001100110011001, out);
            $finish;
        end
        arg_0 = 4'b1101;
        arg_1 = 4'b1110;
        #0;
        if (20'b01100110011001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 222", 20'b01100110011001100110, out);
            $finish;
        end
        arg_0 = 4'b1101;
        arg_1 = 4'b1111;
        #0;
        if (20'b00110011001100110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 223", 20'b00110011001100110011, out);
            $finish;
        end
        arg_0 = 4'b1110;
        arg_1 = 4'b0000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 224", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1110;
        arg_1 = 4'b0001;
        #0;
        if (20'b11101110111011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 225", 20'b11101110111011101110, out);
            $finish;
        end
        arg_0 = 4'b1110;
        arg_1 = 4'b0010;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 226", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b1110;
        arg_1 = 4'b0011;
        #0;
        if (20'b10101010101010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 227", 20'b10101010101010101010, out);
            $finish;
        end
        arg_0 = 4'b1110;
        arg_1 = 4'b0100;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 228", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1110;
        arg_1 = 4'b0101;
        #0;
        if (20'b01100110011001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 229", 20'b01100110011001100110, out);
            $finish;
        end
        arg_0 = 4'b1110;
        arg_1 = 4'b0110;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 230", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b1110;
        arg_1 = 4'b0111;
        #0;
        if (20'b00100010001000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 231", 20'b00100010001000100010, out);
            $finish;
        end
        arg_0 = 4'b1110;
        arg_1 = 4'b1000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 232", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1110;
        arg_1 = 4'b1001;
        #0;
        if (20'b11101110111011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 233", 20'b11101110111011101110, out);
            $finish;
        end
        arg_0 = 4'b1110;
        arg_1 = 4'b1010;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 234", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b1110;
        arg_1 = 4'b1011;
        #0;
        if (20'b10101010101010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 235", 20'b10101010101010101010, out);
            $finish;
        end
        arg_0 = 4'b1110;
        arg_1 = 4'b1100;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 236", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1110;
        arg_1 = 4'b1101;
        #0;
        if (20'b01100110011001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 237", 20'b01100110011001100110, out);
            $finish;
        end
        arg_0 = 4'b1110;
        arg_1 = 4'b1110;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 238", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b1110;
        arg_1 = 4'b1111;
        #0;
        if (20'b00100010001000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 239", 20'b00100010001000100010, out);
            $finish;
        end
        arg_0 = 4'b1111;
        arg_1 = 4'b0000;
        #0;
        if (20'b00000000000000000000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 240", 20'b00000000000000000000, out);
            $finish;
        end
        arg_0 = 4'b1111;
        arg_1 = 4'b0001;
        #0;
        if (20'b11111111111111111111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 241", 20'b11111111111111111111, out);
            $finish;
        end
        arg_0 = 4'b1111;
        arg_1 = 4'b0010;
        #0;
        if (20'b11101110111011101110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 242", 20'b11101110111011101110, out);
            $finish;
        end
        arg_0 = 4'b1111;
        arg_1 = 4'b0011;
        #0;
        if (20'b11011101110111011101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 243", 20'b11011101110111011101, out);
            $finish;
        end
        arg_0 = 4'b1111;
        arg_1 = 4'b0100;
        #0;
        if (20'b11001100110011001100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 244", 20'b11001100110011001100, out);
            $finish;
        end
        arg_0 = 4'b1111;
        arg_1 = 4'b0101;
        #0;
        if (20'b10111011101110111011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 245", 20'b10111011101110111011, out);
            $finish;
        end
        arg_0 = 4'b1111;
        arg_1 = 4'b0110;
        #0;
        if (20'b10101010101010101010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 246", 20'b10101010101010101010, out);
            $finish;
        end
        arg_0 = 4'b1111;
        arg_1 = 4'b0111;
        #0;
        if (20'b10011001100110011001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 247", 20'b10011001100110011001, out);
            $finish;
        end
        arg_0 = 4'b1111;
        arg_1 = 4'b1000;
        #0;
        if (20'b10001000100010001000 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 248", 20'b10001000100010001000, out);
            $finish;
        end
        arg_0 = 4'b1111;
        arg_1 = 4'b1001;
        #0;
        if (20'b01110111011101110111 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 249", 20'b01110111011101110111, out);
            $finish;
        end
        arg_0 = 4'b1111;
        arg_1 = 4'b1010;
        #0;
        if (20'b01100110011001100110 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 250", 20'b01100110011001100110, out);
            $finish;
        end
        arg_0 = 4'b1111;
        arg_1 = 4'b1011;
        #0;
        if (20'b01010101010101010101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 251", 20'b01010101010101010101, out);
            $finish;
        end
        arg_0 = 4'b1111;
        arg_1 = 4'b1100;
        #0;
        if (20'b01000100010001000100 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 252", 20'b01000100010001000100, out);
            $finish;
        end
        arg_0 = 4'b1111;
        arg_1 = 4'b1101;
        #0;
        if (20'b00110011001100110011 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 253", 20'b00110011001100110011, out);
            $finish;
        end
        arg_0 = 4'b1111;
        arg_1 = 4'b1110;
        #0;
        if (20'b00100010001000100010 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 254", 20'b00100010001000100010, out);
            $finish;
        end
        arg_0 = 4'b1111;
        arg_1 = 4'b1111;
        #0;
        if (20'b00010001000100010001 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 255", 20'b00010001000100010001, out);
            $finish;
        end
        $display("TESTBENCH OK", );
        $finish;
    end
    function [19:0] kernel_do_stuff(input reg [3:0] arg_0, input reg [3:0] arg_1);
        reg [3:0] or0;
        reg [3:0] or1;
        reg [3:0] or2;
        reg [3:0] or3;
        reg [3:0] or4;
        reg [3:0] or5;
        reg [19:0] or6;
        reg [3:0] or7;
        localparam ol0 = 4'b0001;
        begin
            or0 = arg_0;
            or1 = arg_1;
            // let b1 = a1.val();
            //
            // let b2 = a2.val();
            //
            // let a1 = b1.dyn_bits();
            //
            // let a2 = b2.dyn_bits();
            //
            // let c = a1 * a2;
            //
            or2 = or0 * or1;
            // let d = c * 1;
            //
            or7 = or2[3:0];
            // let e = 1 * d;
            //
            or3 = ol0 * or7;
            // let f = a1 * b2;
            //
            or4 = or0 * or1;
            // let g = b1 * a2;
            //
            or5 = or0 * or1;
            // signal((c.as_bits(), d.as_bits(), e.as_bits(), f, g, ))
            //
            or6 = { or5, or4, or3, or7, or2 };
            kernel_do_stuff = or6;
        end
    endfunction
endmodule
