// Autogenerated testbench for kernel_shr
module testbench();
    wire [11:0] out;
    reg [11:0] arg_0;
    reg [3:0] arg_1;
    assign out = kernel_shr(arg_0, arg_1);
    initial begin
        arg_0 = 12'sb111111010110;
        arg_1 = 4'b0010;
        #0;
        if (12'sb111111110101 !== out) begin
            $display("ASSERTION FAILED 0x%0h !== 0x%0h CASE 0", 12'sb111111110101, out);
            $finish;
        end
        $display("TESTBENCH OK", );
        $finish;
    end
    function signed [11:0] kernel_shr(input reg signed [11:0] arg_0, input reg [3:0] arg_1);
        reg signed [11:0] or0;
        reg [3:0] or1;
        reg signed [11:0] or2;
        begin
            or0 = arg_0;
            or1 = arg_1;
            // let a = a.val();
            //
            // let b = b.val();
            //
            // signal(a >> b)
            //
            or2 = or0 >>> or1;
            kernel_shr = or2;
        end
    endfunction
endmodule
