pub mod driver;
pub mod mir;
mod rhif_passes;
mod rtl_passes;
mod stage1;
mod stage2;
pub use stage1::CompilationMode;
mod lower_rhif_to_rtl;
pub use driver::compile_design;
pub use stage2::compile as compile_stage2;
