[workspace]

[package]
name = "synhdl"
version = "0.1.0"
edition = "2024"

[dependencies]
derive-syn-parse = "0.2.0"
miette = { version = "7.6.0", features = ["fancy"] }
syn = { version = "2.0.104", features = ["extra-traits", "full"] }
syn-miette = "0.3.0"
