mod compiler_impl;
pub use compiler_impl::compile;
pub mod driver;
mod infer_types;
pub use driver::compile_design;
pub(crate) use infer_types::infer;
pub mod ty;
mod unify;
pub(crate) use unify::UnifyContext;
mod assign_node;
pub(crate) use assign_node::assign_node_ids;
mod ascii;
pub(crate) mod check_inference;
pub(crate) mod check_rhif_flow;
pub(crate) mod check_rhif_type;
mod display_ast;
mod lower_index_to_copy;
mod pass;
mod remove_extra_registers;
