all:
	just clean
	just build
	just serve

clean:
	just plugin
	rm -rf db/*.json

build:
	just plugin
	mdbook build

serve:
	just plugin
	RUST_LOG=info mdbook serve --watcher native

plugin:
	cd ../mdbook-rhdl && cargo build --release
